 
* Circumstellar nebula M1-67 around the Wolf Rayet star WR124

** Previous papers on M1-67

*** HST H alpha images
- [[https://ui.adsabs.harvard.edu/abs/1998Ap&SS.260..181G][Grosdidier et al (1998)]] First epoch HST images. Has some prescient comments:
  : We see many bright resolved knots of emission in the inner nebula, often surrounded by spherical, diffuse material (Fig. 2).
  So they seem to have notice the knots and the shocked shells.
- [[https://ui.adsabs.harvard.edu/abs/2001ApJ...562..753G][Grosdidier et al (2001)]] Analysis of same HST images, together with 
  CFHT spectra. They do lots of statistical analysis of structure functions and PDFs and try to relate it to turbulence. However, when they try and remove the stars from the HST image, they also remove the knots, which is not ideal.
- 
*** Infrared observations
- [[https://ui.adsabs.harvard.edu/abs/2016A&A...588A..92V][Vamvatira-Nakou et al (2016)]] Analysis of Herschel observations, plus a dust model
*** Kinematics
- Zavala et al. 2022
  - Maybe the halo corresponds to the systemic velocity
** Plan for poster
This is in a [[file:m1-67-bowshocks-poster.md][separate markdown file]] for greater accessibility

** Measuring the knots
- Region file
  - [[file:../../../Work/WR124-HST/m1-67-globules.reg]]
- Number of globules: 169
- Number of isolated globules where we can hope to measure the shell: 49
** JWST images
- [[https://mast.stsci.edu/portal/Mashup/Clients/Mast/Portal.html?searchQuery=%7B%22service%22%3A%22CAOMDB%22%2C%22inputText%22%3A%22wr124%22%2C%22paramsService%22%3A%22Mast.Caom.Cone%22%2C%22title%22%3A%22MAST%3A%20wr124%22%2C%22columns%22%3A%22*%22%2C%22caomVersion%22%3Anull%7D][Link to search of MIRI and NIRCAM images]]
*** Available filters and corresponding spectral features
**** NIRCAM
[[https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters][Documentation]]
- f090w
  - 0.795 - 1.005	
  - [S III] 9069 AA, 9533 AA
  - H I Paschen lines down to 0.9548590 H I 3-8 
- f150w
  - 1.331 - 1.668
  - He I 1.3415350934 1s.3p-1s.5s 1Po-1S
  - He I 1.508777481 1s.3s-1s.4p  1S-1Po
  - H I Brackett lines down to 1.6411674 H I 4-12
- f210m
  - 1.992 - 2.201
  - Br gamma H I 4-7 2.166120 micron
  - He I 2.058690463 1s.2s-1s.2p  1S-1Po
  - H_2 2.12 micron and others
- f335m
  - 3.177 - 3.537
  - PAH feature at 3.3 micron (typical width 0.04 micron)
    - Plus weaker feature at 3.4 micron
    - Plus broad pedestal 3.25 - 3.6
  - Pfund delta 3.296992 H I 5-9
  - Weak He I intercombination line
    - 3.36408868 He I] E1 1s.3s-1s.3p  3S-1Po  1 - 1  A=1.460e-01 
- f444w
  - 3.881 - 4.982 (W=1.101)
  - He I lines are all weak (n=5 or higher for upper levels)
  - [Mg IV] ground config fine structure line
    - 4.4867 [Mg IV] M1 2s2.2p5-2s2.2p5 2Po-2Po 3/2 - 1/2
  - Br alpha H I 4-5 4.052262 micron
  - Pfund beta H I 5-7 4.653778 micron
- f470n
  - 4.683 - 4.733 (W=0.05)
  - Pfund beta H I 5-7 4.653778 micron
  - H_2 4.695 micron
  - Unknown 4.673 micron
***** Strange behavior of the f470n filter
- Only the H_2 4.695 micron line is comfortably within the filter bandpass
- The H I lines are all too far outside the filter to contribute significantly
- This means that most of the emission must be continuum
  - That is exactly what is seen in Orion
  - Brightness of F470N and F480M are similar
  - Brightness is in MJy/sr, so that is per Hz


**** MIRI Imaging
***** Summary table from Spitzer spectra
  | Filter | Component       | Fraction |
  |--------+-----------------+----------|
  | F770W  | CONTINUUM       |     0.54 |
  | F770W  | [Ar II] 6.985   |     0.36 |
  | F770W  | H I 7.460       |     0.07 |
  | F770W  | PAH 8.6         |     0.03 |
  |--------+-----------------+----------|
  | F1130W | CONTINUUM       |      0.9 |
  | F1130W | PAH 11.2        |     0.09 |
  | F1130W | [Ne III] 10.863 |    0.005 |
  | F1130W | UIL 11.01       |    0.003 |
  | F1130W | UIL 11.54       |    0.003 |
  |--------+-----------------+----------|
  | F1280W | CONTINUUM       |     0.75 |
  | F1280W | H I 12.372      |     0.05 |
  | F1280W | [Ne II] 12.814  |     0.19 |
  | F1280W | PAH 12.7        |    0.003 |
  |--------+-----------------+----------|
  | F1800W | CONTINUUM       |      0.8 |
  | F1800W | [S III] 18.713  |     0.17 |
  | F1800W | H I 19.062      |     0.03 |
  |--------+-----------------+----------|
***** Predictions for behavior of each filter
- Derived from Spitzer spectra
- F770W has roughly equal contribution from LINES and CONTINUUM
  - Some contribution from PAH but 3 times less than for F1130W
- F1130W is CONTINUUM dominated for the entire nebula with 10% PAH
  - But can plausibly be PAH dominated in small regions
  - Negligible LINES contribution
- F1280W has significant CONTINUUM and LINES contribution
  - But CONTINUUM dominates more than in F770W
  - Negligible PAH contribution
- F1800W is dominated by CONTINUUM
  - with 20% LINES contribution ([S III], so higher ionization)
  - no PAH at all
 
***** Predictions for what factors influence the colors
- f1800w / f1280w
  1. Variations in continuum slope
     - thermal dust emission increases to red
     - large wave difference of 50% will amplify variations in slope
     - Roberto calculated this on blackboard [2023-11-08 Wed]
       - Assume I_\nu \propto \lambda^\beta
       - Observed log10(18/12.8) varied from 0.2 to 0.8 with median 0.5
       - => Slope \beta varies from +1 to +6 with median +3
       - Consistent with appearance of JWST spectra, although not so much with Spitzer
       - Remember that SED is I_\nu / \lambda so should have median slope 2
  2. Variations in ionization of gas
     - High ionization favors [S III], so f1800w
     - Low ionization favors [Ne II], so f1280w
- f1280w / f1130w
  1. Variations in continuum slope
     - This might be dominant effect on the scale of the entire nebula since both filters are dominated by continuum (80 to 90%)
     - BUT small wavelength difference (10%) will suppress the impact on the ratio of variations in slope
     - Also, it would predict a positive correlation of (f1280w / f1130w) with (f1800w / f1280w), whereas we observe a negative correlation
  2. 
       
***** Detailed inventory of each filter
- f770w
  - 6.5 - 8.7 (W = 2.2)
  - Continuum is a bit discrepant between SL1 and SL2
    - We should really work in F_lam ~ F_nu / lam^2 when we are considering a broad range of lambda
      - But really no need since fractional wave width is no more than 15%
    - Around 7 microns, SL2 gives F_nu = 1 - 2 (see below), climbing with lambda
    - Around 8.5 microns, SL1 gives F_nu = 4
    - So factor of 2 or 3 discrepancy,
      - possibly due to bad BG subtraction of SL2 (it does go negative at shorter waves)
      - or real difference due to different apertures
      - coincidence of PAH 7.7 feature with the overlap does not help the matching of continuum either
    - /We will use a compromise continuum level of 3 for the filter average/
  - [Ar II] 6.985 is extremely strong
    - Measurement in SL2
    - Continuum level between 6.6 and 7.3: 0.5 (1.0 + 2.0) = 1.5
    - Peak @ 6.98: 37.6 - 1.5 = 36.1
    - FWHM: 0.06 micron
    - EW = 36.1 0.06 / 1.5 = 1.444 micron
  - H I 7.460 is a minor contribution
    - Also includes He I 7.455 (and potentially [Cl IV] 7.447)
    - Continuum level between 7.4 and 7.6: 2
    - Peak @ 7.47: 8.5 - 2 = 6.5
    - FWHM: 0.09 micron
    - EW = 6.5 0.09 / 2 = 0.29 micron
  - PAH features at 7.7 and 8.6 microns should contribute
    - In Spitzer spectra, only 8.6 is seen clearly
      - Measurement in SL1
      - Continuum: 4
      - Peak @ 8.53: 5.27 - 4 = 1.27
      - FWHM: 0.4 microns
      - EW = 1.27 0.4 / 4 = 0.13 micron
    - Although 7.7 should be stronger by a factor of about 2
    - The H I 7.46 gets in the way
    - And also hampered by being at join between SL1 and SL2 modules in spectrograph
  - Relative contributions:
    - Summed cont plus line EWs: 2.2 + 1.444 + 0.29 + 0.13 = 4.064
    - Continuum: 2.2 / 4.064 = 0.54
    - [Ar II] 6.985: 1.444 / 4.064 = 0.36
    - H I 7.460: 0.29 / 4.064 = 0.07
    - PAH 8.6: 0.13 / 4.064 = 0.03
    - 
- f1130w
  - 10.9 - 11.7 (W = 0.8) narrowest of filters
  - PAH 11.2 might be the dominant feature
    - Measurement in SL1 (short-low module)
      - Continuum level between 11 and 11.6: 0.5 (5.7 + 7.2) = 6.45 +/- 0.75
      - Peak @ 11.3: 9.04 - 6.45 = 2.6
      - FWHM: 0.2 micron
      - EW = 2.6 0.2 / 6.45 = 0.08 micron
      - Relative contribution: 0.08 / (0.08 + 0.8) = 0.09
    - Measurement in SH (short-high module)
      - Continuum level between 11 and 11.6: 90
      - Narrow Peak @ 11.31: 195 - 90 = 105
      - Narrow FWHM: 0.036 micron
      - Narrow EW: 105 0.036 / 90 = 0.042 micron
      - Broad Peak @ 11.23: 104 - 90 = 14
      - Broad FWHM: 0.2 micron
      - Broad EW: 14 0.2 / 90 = 0.031 micron
      - Relative contribution:
        - Narrow 0.042 / (0.042 + 0.031 + 0.8) = 0.05
        - Broad 0.031 / (0.042 + 0.031 + 0.8) = 0.04
  - So both high and low res spectra give total PAH contribution of 9%
  - The other 90% is continuum since there are no strong lines in the pass band
  - There will be a tiny contribution from [Ne III] 10.863
    - Throughput is only 0.2 times maximum
    - Line peak is 0.5 of narrow PAH peak, and similar width
    - So contribution of 0.5% to total
  - There are also unidentified lines or features at 11.01 and 11.54
    - Total contribution of order 1%
    - Work out EW of 11.54 line
      - Cont level is 95
      - Excess pixels: 102, 105, 107, 99, 96
        - vsum([102, 105, 107, 99, 96]) - 5 95 = 34
      - Pixel size: 11.58489 - 11.57600 = 8.89e-3 micron
      - So EW = 34 8.89e-3 / 95 = 0.003 Micron
      - Relative contribution is 0.003 / (0.8 + 0.09 + 0.003 + 0.003) = 0.003
- f1280w
  - 11.6 - 14.1 (W=2.5)
  - Continuum levels:
    - SL1: 7.3 to 11.9, so roughly 9.6
    - SH: 93 to 87, so roughly 90
  - H I 12.372
    - SL1:
      - local cont level = 9
      - excess pixels: 11.95, 15.35, 12.77, 11.98
        - vsum([11.95, 15.35, 12.77, 11.98]) - 4 9 = 16.05
      - pixel size: 12.50124 - 12.43915 = 0.06209 micron
      - EW = 16.05 0.06209 / 9.6 = *0.10 microns*
      - Note that we are now doing the EW in the best way I think
        - subtract local continuum
        - but divide by average continuum over full filter bandpass
        - we were not entirely consistent with that above, but it does not really matter
    - SH:
      - local cont level = 93
      - excess pixels
        vsum([98.57770, 109.0163, 120.5194, 156.2358, 252.6667, 349.4323, 404.9628, 401.0829, 335.2653, 215.6403, 145.0898, 108.7390, 99.62641, 98.39452, 96.95181]) - 15 93
        = 1597.20104
      - pixel size: 12.44439 - 12.43502 = 9.37e-3
      - EW = 1597 9.37e-3 / 90 = *0.166 microns*
      - So slightly larger in SH, maybe due to smaller aperture
  - [Ne II] 12.814
    - SH:
      - local cont level = 90
      - excess pixels
        vsum([96.35126, 98.83986, 98.33226, 105.5441, 123.4146, 210.1461, 400.2357, 1368.507, 2619.267, 1245.834, 312.5799, 133.4844, 103.5154, 99.60088, 95.13274, 93.56950]) - 16 90
        = 5764.3547
      - pixel size: 12.82066 - 12.81065 = 0.01 microns
      - EW = 5764 0.01 / 90 = *0.64 microns*
    - SL1 but this includes blend with PAH feature
      - local cont level: 9.5
      - excess pixels
        vsum([13.34165, 15.93223, 23.00680, 65.62168, 144.8405, 100.5812, 24.06742, 11.31612, 10.00899, 9.607738]) - 10 9.5
        = 323.324328
      - pixel size: 12.87381 - 12.81171 = 0.0621
      - EW = 323 0.0621 / 9.6 = *2.1 microns*
      - /This is way higher than in the high resolution spectrum!/
  - PAH 12.70
    - This can only be measured separately on SH
      #+begin_src literate-calc
        pixel size = 12.70042 - 12.69039
        local continuum = 95
        global continuum = 90
        excess pixels = [ 99.08077, 101.8942, 122.5339, 119.4511, 106.9248, 96.35126 ]
        line flux = (vsum(excess pixels) - local continuum vcount(excess pixels)) pixel size 
        EW = line flux / global continuum
      #+end_src

      #+RESULTS:
      : EW: 8.49608201e-3
      - So that is really small: EW < 0.01 micron
      - On the face of it, it would seem this narrow feature is probably not from PAH, but may be a weak emission line
  - Additional weak lines
    - 12.58 microns
      - similar strength to 12.7, EW < 0.01 micron, but broader
    - 
  - Relative contributions from EWs for SH
    - Denominator: 2.5 + 0.166 + 0.64 + 0.01 = 3.316
    - Continuum: 2.5 / 3.316 = 0.75
    - H I 12.372: 0.166 / 3.316 = 0.05
    - [Ne II] 12.814: 0.64 / 3.316 = 0.19
    - PAH 12.7: 0.01 / 3.316 = 0.003
  - Relative contributions from EWs for SL1
    - Denominator: 2.5 + 0.1 + 2.1 = 4.7
    - Continuum: 2.5 / 4.7 = 0.53
    - H I 12.372: 0.1 / 4.7 = 0.02
    - ([Ne II] 12.814 + PAH 12.7): 2.1 / 4.7 = 0.45
- f1800w
  - 16.5 - 19.5 (W=3.0)
  - Continuum levels
    - SH: 110 to 150, so roughly 130
    - LL2: 8 to 16, so roughly 12
  - [S III] 18.713
    - LL2:
      #+begin_src literate-calc
        pixel size = 18.75956 - 18.66787 
        local continuum = 13
        global continuum = 12
        excess pixels = [13.81146, 14.10895, 15.20396, 37.70677, 55.64561, 34.55833]
        line flux = (vsum(excess pixels) - local continuum vcount(excess pixels)) pixel size 
        EW = line flux / global continuum
      #+end_src

      #+RESULTS:
      : EW: 0.710865540433
    - SH:
      #+begin_src literate-calc
        pixel size = 18.71894 - 18.70461 
        local continuum = 150
        global continuum = 130
        excess pixels = [149.6441, 159.3758, 162.137, 167.0328, 177.1403, 197.2899, 329.7, 801.2004, 1993.435, 1779.581, 617.2753, 225.6703, 179.5071, 164.7809, 157.2606, 161.6798, 166.8396, 163.0172]
        line flux = (vsum(excess pixels) - local continuum vcount(excess pixels)) pixel size 
        EW = line flux / global continuum
      #+end_src  

      #+RESULTS:
      : EW: 0.556948358023

  - H I 19.062
    - LL2:
      #+begin_src literate-calc
        pixel size = 18.75956 - 18.66787 
        local continuum = 16  
        global continuum = 12
        excess pixels = [20.0934, 19.12052, 19.08846, 17.71572, 17.23154, 16.76833, 16.38189, 16.22759]
        line flux = (vsum(excess pixels) - local continuum vcount(excess pixels)) pixel size 
        EW = line flux / global continuum
      #+end_src

      #+RESULTS:
      : EW: 0.111765907542
    - SH:
       #+begin_src literate-calc
         pixel size = 18.71894 - 18.70461 
         local continuum = 150
         global continuum = 130
         excess pixels = [165.4142, 167.0518, 169.862, 171.248, 167.1111, 173.8094, 188.3421, 180.972, 178.9863, 188.7144, 190.8224, 201.0344, 245.9152, 280.4614, 297.4046, 302.9159, 242.5485, 198.7767, 176.3045, 162.2901, 160.6702, 162.6303, 160.3429, 160.4061]
         line flux = (vsum(excess pixels) - local continuum vcount(excess pixels)) pixel size 
         EW = line flux / global continuum
      #+end_src  

      #+RESULTS:
      : EW: 0.1205962645
  - Other weak lines:
    - None are important
  - Relative contributions from EWs for SH
    - Denominator: 3.0 + 0.56 + 0.12 = 3.68
    - Continuum: 3.0 / 3.68 = 0.815
    - [S III] 18.713: 0.56 / 3.68 = 0.152
    - H I 19.062: 0.12 / 3.68 = 0.033
  - Relative contributions from EWs for SL1
    - Denominator: 3.0 + 0.711 + 0.112 = 3.823
    - Continuum: 3.0 / 3.823 = 0.785
    - [S III] 18.713: 0.711 / 3.823 = 0.186
    - H I 19.062: 0.112 / 3.823 = 0.029

    


*** Pandeia engine
This seems to be te easiest way to get access to the filter transmission curves

**** Installation
- I am following the instructions at https://outerspace.stsci.edu/display/PEN/Pandeia+Engine+Installation
  - I got to that page from https://jwst-docs.stsci.edu/jwst-exposure-time-calculator-overview/jwst-etc-pandeia-engine-tutorial, which has a more general description of what the package does
    : In addition to its web UI, the JWST ETC (hereafter Pandeia) may be used as a Python module, and incorporated into Python scripts or programs. This tutorial provides information for installing the JWST ETC as a Python module, on the JWST ETC Python programming API, and on producing calculations with the JWST ETC Python interface that might be difficult or impossible to generate through the web interface.
  - Installed the python library with pip
  - Installed the required and additional data files
    - Pandeia files in ~~/Work/pandeia-data~
    - CDBS files in ~~/Work/synphot-data~
  - Set environment variables in profile file (in my case, in ~.zshrc~)
    #+begin_src sh
      export PYSYN_CDBS=${HOME}/Work/synphot-data
      export pandeia_refdata=${HOME}/Work/pandeia-data
    #+end_src

    #+RESULTS:

  - Test installation
    #+begin_src sh :results verbatim
      export PYSYN_CDBS=${HOME}/Work/synphot-data
      export pandeia_refdata=${HOME}/Work/pandeia-data
      python -c "import pandeia.engine; pandeia.engine.pandeia_version()"
    #+end_src

    #+RESULTS:
    : Pandeia Engine version:  3.0
    : Pandeia RefData version:  3.0
    : Synphot Data:  /Users/will/Work/synphot-data
    
**** Instrument throughputs
- Based on [[https://jwst-docs.stsci.edu/jwst-exposure-time-calculator-overview/jwst-etc-pandeia-engine-tutorial/jwst-etc-instrument-throughputs][Pandeia Quickstart]] and [[https://jwst-docs.stsci.edu/jwst-exposure-time-calculator-overview/jwst-etc-pandeia-engine-tutorial/pandeia-quickstart][JWST ETC Instrument Throughputs]] docs
- First construct a suitable config dict
  #+begin_src python :return config :results verbatim
    from pandeia.engine.calc_utils import build_default_calc
    calculation = build_default_calc("jwst", "miri", "imaging")
    config = calculation["configuration"]
  #+end_src

  #+RESULTS:
  : {'detector': {'nexp': 1, 'ngroup': 100, 'nint': 1, 'readout_pattern': 'fastr1', 'subarray': 'full'}, 'instrument': {'aperture': 'imager', 'disperser': None, 'filter': 'f560w', 'instrument': 'miri', 'mode': 'imaging'}}
- Now try and get the transmission curve
  #+begin_src python :return rslt
    import numpy as np
    from pandeia.engine.calc_utils import build_default_calc
    from pandeia.engine.instrument_factory import InstrumentFactory

    calculation = build_default_calc("jwst", "miri", "imaging")
    config = calculation["configuration"]
    config["instrument"]["filter"] = "f770w"

    # set up your wavelengths
    wave = np.linspace(6.0, 9.0, 31)

    # create a configured instrument
    instrument_factory = InstrumentFactory(config=config)

    # get the throughput of the instrument over the desired wavelength range
    eff = instrument_factory.get_total_eff(wave)

    rslt = list(zip(wave, np.round(eff, 3)))
  #+end_src

  #+RESULTS:
  | 6.0 |   0.0 |
  | 6.1 |   0.0 |
  | 6.2 |   0.0 |
  | 6.3 |   0.0 |
  | 6.4 |   0.0 |
  | 6.5 | 0.014 |
  | 6.6 | 0.211 |
  | 6.7 | 0.274 |
  | 6.8 | 0.339 |
  | 6.9 | 0.322 |
  | 7.0 | 0.333 |
  | 7.1 | 0.358 |
  | 7.2 | 0.352 |
  | 7.3 | 0.364 |
  | 7.4 | 0.351 |
  | 7.5 | 0.372 |
  | 7.6 | 0.351 |
  | 7.7 | 0.372 |
  | 7.8 | 0.374 |
  | 7.9 | 0.374 |
  | 8.0 | 0.373 |
  | 8.1 | 0.382 |
  | 8.2 | 0.375 |
  | 8.3 | 0.378 |
  | 8.4 | 0.366 |
  | 8.5 | 0.373 |
  | 8.6 | 0.358 |
  | 8.7 | 0.143 |
  | 8.8 | 0.009 |
  | 8.9 | 0.001 |
  | 9.0 |   0.0 |
- That seems to have worked well for f770w
*** Alignment of JWST images

**** Try and do a better job of alignment
- We can use the scripts that I wrote for multifrecuencia class
- 

***** The HST images
- In the notebook analysis, I used the Ha image from the second epoch
  - ~11137_01~
- But we want to align the wide band images too, which I suspect are only the first epoch
  - ~06787_01~

****** Copy the original HST images to working directory
And give them shorter file names that include the year
#+begin_src sh :dir data :results verbatim
  D=/Users/will/Work/WR124-HST/MAST_2023-04-03T1936/HLA/
  ID=06787
  for FN in f656n f675w f555w; do
      cp -av $D/hst_${ID}_01_wfpc2_${FN}_wf/hst_${ID}_01_wfpc2_${FN}_wf_drz.fits wr124-hst-1997-${FN}.fits
  done
  ID=11137
  for FN in f656n; do
      cp -av $D/hst_${ID}_01_wfpc2_${FN}_wf/hst_${ID}_01_wfpc2_${FN}_wf_drz.fits wr124-hst-2008-${FN}.fits
  done
#+end_src

#+RESULTS:
: /Users/will/Work/WR124-HST/MAST_2023-04-03T1936/HLA//hst_06787_01_wfpc2_f656n_wf/hst_06787_01_wfpc2_f656n_wf_drz.fits -> wr124-hst-1997-f656n.fits
: /Users/will/Work/WR124-HST/MAST_2023-04-03T1936/HLA//hst_06787_01_wfpc2_f675w_wf/hst_06787_01_wfpc2_f675w_wf_drz.fits -> wr124-hst-1997-f675w.fits
: /Users/will/Work/WR124-HST/MAST_2023-04-03T1936/HLA//hst_06787_01_wfpc2_f555w_wf/hst_06787_01_wfpc2_f555w_wf_drz.fits -> wr124-hst-1997-f555w.fits
: /Users/will/Work/WR124-HST/MAST_2023-04-03T1936/HLA//hst_11137_01_wfpc2_f656n_wf/hst_11137_01_wfpc2_f656n_wf_drz.fits -> wr124-hst-2008-f656n.fits

****** Do HST local background subtraction
#+begin_src sh :dir data :results verbatim
  for f in wr124-hst-????-f????.fits; do
      python ../scripts/findbg-local.py $f
  done

#+end_src

#+RESULTS:

****** Source finding in HST images
First try with brightness limit of 2 and radius of 3
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-sources.py wr124-hst-1997-f656n_BGSUB.fits 3.0 2.0
#+end_src

#+RESULTS:
: Source list saved to wr124-hst-1997-f656n_BGSUB-sources-fwhm3.0-thresh2.ecsv
: Region file saved to wr124-hst-1997-f656n_BGSUB-sources-fwhm3.0-thresh2.reg

#+begin_src sh :dir data :results verbatim
  python ../scripts/find-sources.py wr124-hst-2008-f656n_BGSUB.fits 3.0 2.0
#+end_src

#+RESULTS:
: Source list saved to wr124-hst-2008-f656n_BGSUB-sources-fwhm3.0-thresh2.ecsv
: Region file saved to wr124-hst-2008-f656n_BGSUB-sources-fwhm3.0-thresh2.reg

Try reducing brightness limit and radius

#+begin_src sh :dir data :results verbatim
  python ../scripts/find-sources.py wr124-hst-1997-f656n_BGSUB.fits 2.0 1.0
#+end_src

#+RESULTS:
: Source list saved to wr124-hst-1997-f656n_BGSUB-sources-fwhm2.0-thresh1.ecsv
: Region file saved to wr124-hst-1997-f656n_BGSUB-sources-fwhm2.0-thresh1.reg
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-sources.py wr124-hst-2008-f656n_BGSUB.fits 2.0 1.0
#+end_src

#+RESULTS:
: Source list saved to wr124-hst-2008-f656n_BGSUB-sources-fwhm2.0-thresh1.ecsv
: Region file saved to wr124-hst-2008-f656n_BGSUB-sources-fwhm2.0-thresh1.reg

This works the best. It looks like we have about 20 stars coincident between the two epochs in Ha

Now try the wide band. Increase threshold by factor of 10 since stars are brighter in this filter
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-sources.py wr124-hst-1997-f675w_BGSUB.fits 2.0 10.0
#+end_src

#+RESULTS:
: Source list saved to wr124-hst-1997-f675w_BGSUB-sources-fwhm2.0-thresh10.ecsv
: Region file saved to wr124-hst-1997-f675w_BGSUB-sources-fwhm2.0-thresh10.reg

This finds a superset of the same stars

And the V band

#+begin_src sh :dir data :results verbatim
  python ../scripts/find-sources.py wr124-hst-1997-f555w_BGSUB.fits 2.0 10.0
#+end_src

#+RESULTS:
: Source list saved to wr124-hst-1997-f555w_BGSUB-sources-fwhm2.0-thresh10.ecsv
: Region file saved to wr124-hst-1997-f555w_BGSUB-sources-fwhm2.0-thresh10.reg

****** Source matching and aligning of HST images

******* Two epochs of H alpha
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-hst-1997-f656n_BGSUB wr124-hst-2008-f656n_BGSUB \
         fwhm2.0-thresh1 fwhm2.0-thresh1 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --object-name wr124 --combo-prefix wr124-hst-f656n-1997-TO-2008
#+end_src

#+RESULTS:
: Statistics based on 28 coincident sources
: Mean displacement in RA: -2.45 +/- 4.04 marcsec
: Mean displacement in Dec: -20.85 +/- 6.88 marcsec
: Median displacement in RA: 0.95 +/- 4.56 marcsec
: Median displacement in Dec: -25.26 +/- 4.88 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-hst-f656n-1997-TO-2008-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-f656n-1997-TO-2008-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-hst-f656n-1997-TO-2008-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-f656n-1997-TO-2008-OFFSETS-CORR.pdf]]

******* H alpha versus continuum for first epoch
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-hst-1997-f656n_BGSUB wr124-hst-1997-f675w_BGSUB \
         fwhm2.0-thresh1 fwhm2.0-thresh10 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --object-name wr124 --combo-prefix wr124-hst-1997-f656n-TO-f675w
#+end_src

#+RESULTS:
: Statistics based on 43 coincident sources
: Mean displacement in RA: 6.42 +/- 2.30 marcsec
: Mean displacement in Dec: 46.07 +/- 8.35 marcsec
: Median displacement in RA: 6.90 +/- 2.89 marcsec
: Median displacement in Dec: 53.72 +/- 2.74 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-hst-1997-f656n-TO-f675w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-1997-f656n-TO-f675w-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-hst-1997-f656n-TO-f675w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-1997-f656n-TO-f675w-OFFSETS-CORR.pdf]]

******* Green to red continuum
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-hst-1997-f555w_BGSUB wr124-hst-1997-f675w_BGSUB \
         fwhm2.0-thresh10 fwhm2.0-thresh10 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --object-name wr124 --combo-prefix wr124-hst-1997-f555w-TO-f675w
#+end_src

#+RESULTS:
: Statistics based on 93 coincident sources
: Mean displacement in RA: -12.09 +/- 1.46 marcsec
: Mean displacement in Dec: 54.96 +/- 3.72 marcsec
: Median displacement in RA: -11.81 +/- 1.00 marcsec
: Median displacement in Dec: 59.20 +/- 1.13 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-hst-1997-f555w-TO-f675w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-1997-f555w-TO-f675w-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-hst-1997-f555w-TO-f675w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-1997-f555w-TO-f675w-OFFSETS-CORR.pdf]]


******* H alpha versus green continuum
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-hst-1997-f656n_BGSUB wr124-hst-1997-f555w_BGSUB \
         fwhm2.0-thresh1 fwhm2.0-thresh10 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --object-name wr124 --combo-prefix wr124-hst-1997-f656n-TO-f555w
#+end_src

#+RESULTS:
: Statistics based on 43 coincident sources
: Mean displacement in RA: 17.14 +/- 2.54 marcsec
: Mean displacement in Dec: -4.34 +/- 2.21 marcsec
: Median displacement in RA: 18.26 +/- 2.11 marcsec
: Median displacement in Dec: -5.80 +/- 2.28 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-hst-1997-f656n-TO-f555w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-1997-f656n-TO-f555w-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-hst-1997-f656n-TO-f555w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-1997-f656n-TO-f555w-OFFSETS-CORR.pdf]]

******* H alpha 2008 to red continuum 1997
- We want to use the 1997 f675w image as the reference since it has the most accurate transformation to the GAIA frame

#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-hst-2008-f656n_BGSUB wr124-hst-1997-f675w_BGSUB \
         fwhm2.0-thresh1 fwhm2.0-thresh10 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --object-name wr124 --combo-prefix wr124-hst-2008-f656n-TO-1997-f675w
#+end_src

#+RESULTS:
: Statistics based on 29 coincident sources
: Mean displacement in RA: 9.84 +/- 4.38 marcsec
: Mean displacement in Dec: 64.21 +/- 13.98 marcsec
: Median displacement in RA: 11.95 +/- 4.07 marcsec
: Median displacement in Dec: 78.40 +/- 7.17 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-hst-2008-f656n-TO-1997-f675w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-2008-f656n-TO-1997-f675w-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-hst-2008-f656n-TO-1997-f675w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-2008-f656n-TO-1997-f675w-OFFSETS-CORR.pdf]]

******* Help on script
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py --help
#+end_src

#+RESULTS:
#+begin_example
Usage: find-offset.py [OPTIONS] FILE_PREFIXES... CATALOG_SUFFIXES...

Arguments:
  FILE_PREFIXES...     [required]
  CATALOG_SUFFIXES...  [required]

Options:
  --maximum-separation-arcsec FLOAT
                                  [default: 1.0]
  --maximum-radius-arcsec FLOAT
  --minimum-radius-arcsec FLOAT
  --object-name TEXT              [default: ngc 346]
  --install-completion            Install completion for the current shell.
  --show-completion               Show completion for the current shell, to
                                  copy it or customize the installation.

  --help                          Show this message and exit.
#+end_example

****** TODO Apply shifts to HST images
- We will use the 1997 Ha image as the reference and do WCS adjustments to all the others
- We were finding the displacements from A \to B, which is (B - A)
- So, if we want to correct the B coordinates to the A ones, then we need to subtract those
  - B - (B - A) = A




***** JWST images

****** Copy the original JWST images to working directory
#+begin_src sh :dir data :results verbatim
  D=/Users/will/Work/WR124-JWST/MAST_2023-09-13T2208/JWST
  for FN in f090w f150w f210m f335m f444w; do
      cp -av $D/jw02730-o001_t013_nircam_clear-${FN}/jw02730-o001_t013_nircam_clear-${FN}_i2d.fits wr124-jwst-nircam-2022-${FN}.fits
  done
  for FN in f470n; do
      cp -av $D/jw02730-o001_t013_nircam_f444w-${FN}/jw02730-o001_t013_nircam_f444w-${FN}_i2d.fits wr124-jwst-nircam-2022-${FN}.fits
  done
  for FN in f1130w f1280w f1800w f770w; do
      cp -av $D/jw02730-o002_t013_miri_${FN}/jw02730-o002_t013_miri_${FN}_i2d.fits wr124-jwst-miri-2022-${FN}.fits
  done
#+end_src

#+RESULTS:
#+begin_example
/Users/will/Work/WR124-JWST/MAST_2023-09-13T2208/JWST/jw02730-o001_t013_nircam_clear-f090w/jw02730-o001_t013_nircam_clear-f090w_i2d.fits -> wr124-jwst-nircam-2022-f090w.fits
/Users/will/Work/WR124-JWST/MAST_2023-09-13T2208/JWST/jw02730-o001_t013_nircam_clear-f150w/jw02730-o001_t013_nircam_clear-f150w_i2d.fits -> wr124-jwst-nircam-2022-f150w.fits
/Users/will/Work/WR124-JWST/MAST_2023-09-13T2208/JWST/jw02730-o001_t013_nircam_clear-f210m/jw02730-o001_t013_nircam_clear-f210m_i2d.fits -> wr124-jwst-nircam-2022-f210m.fits
/Users/will/Work/WR124-JWST/MAST_2023-09-13T2208/JWST/jw02730-o001_t013_nircam_clear-f335m/jw02730-o001_t013_nircam_clear-f335m_i2d.fits -> wr124-jwst-nircam-2022-f335m.fits
/Users/will/Work/WR124-JWST/MAST_2023-09-13T2208/JWST/jw02730-o001_t013_nircam_clear-f444w/jw02730-o001_t013_nircam_clear-f444w_i2d.fits -> wr124-jwst-nircam-2022-f444w.fits
/Users/will/Work/WR124-JWST/MAST_2023-09-13T2208/JWST/jw02730-o001_t013_nircam_f444w-f470n/jw02730-o001_t013_nircam_f444w-f470n_i2d.fits -> wr124-jwst-nircam-2022-f470n.fits
/Users/will/Work/WR124-JWST/MAST_2023-09-13T2208/JWST/jw02730-o002_t013_miri_f1130w/jw02730-o002_t013_miri_f1130w_i2d.fits -> wr124-jwst-miri-2022-f1130w.fits
/Users/will/Work/WR124-JWST/MAST_2023-09-13T2208/JWST/jw02730-o002_t013_miri_f1280w/jw02730-o002_t013_miri_f1280w_i2d.fits -> wr124-jwst-miri-2022-f1280w.fits
/Users/will/Work/WR124-JWST/MAST_2023-09-13T2208/JWST/jw02730-o002_t013_miri_f1800w/jw02730-o002_t013_miri_f1800w_i2d.fits -> wr124-jwst-miri-2022-f1800w.fits
/Users/will/Work/WR124-JWST/MAST_2023-09-13T2208/JWST/jw02730-o002_t013_miri_f770w/jw02730-o002_t013_miri_f770w_i2d.fits -> wr124-jwst-miri-2022-f770w.fits
#+end_example

****** Do JWST local background subtraction
Do all the NIRCAM filters first

#+header: :prologue exec 2>&1 :epilogue :
#+begin_src sh :dir data :results verbatim
  for FN in f090w f150w f210m f335m f444w f470n; do
      time python ../scripts/findbg-local.py wr124-jwst-nircam-2022-${FN}.fits
  done
#+end_src

#+RESULTS:
#+begin_example
WARNING: FITSFixedWarning: 'datfix' made the change 'Set DATE-BEG to '2022-06-03T06:35:24.581' from MJD-BEG.
Set DATE-AVG to '2022-06-03T06:52:40.729' from MJD-AVG.
Set DATE-END to '2022-06-03T07:09:56.817' from MJD-END'. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   -82.793158 from OBSGEO-[XYZ].
Set OBSGEO-B to   -31.526408 from OBSGEO-[XYZ].
Set OBSGEO-H to 1653717953.818 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]
WARNING: Input data contains invalid values (NaNs or infs), which were automatically masked. [photutils.background.background_2d]

real	0m13.047s
user	0m10.931s
sys	0m2.341s
WARNING: FITSFixedWarning: 'datfix' made the change 'Set DATE-BEG to '2022-06-03T07:13:31.554' from MJD-BEG.
Set DATE-AVG to '2022-06-03T07:30:47.696' from MJD-AVG.
Set DATE-END to '2022-06-03T07:48:03.790' from MJD-END'. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   -82.780435 from OBSGEO-[XYZ].
Set OBSGEO-B to   -31.535128 from OBSGEO-[XYZ].
Set OBSGEO-H to 1653849940.851 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]
WARNING: Input data contains invalid values (NaNs or infs), which were automatically masked. [photutils.background.background_2d]

real	0m12.342s
user	0m10.826s
sys	0m2.247s
WARNING: FITSFixedWarning: 'datfix' made the change 'Set DATE-BEG to '2022-06-03T05:36:53.693' from MJD-BEG.
Set DATE-AVG to '2022-06-03T06:04:02.984' from MJD-AVG.
Set DATE-END to '2022-06-03T06:31:17.715' from MJD-END'. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   -82.806568 from OBSGEO-[XYZ].
Set OBSGEO-B to   -31.517218 from OBSGEO-[XYZ].
Set OBSGEO-H to 1653578937.800 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]
WARNING: Input data contains invalid values (NaNs or infs), which were automatically masked. [photutils.background.background_2d]

real	0m13.507s
user	0m11.649s
sys	0m2.360s
WARNING: FITSFixedWarning: 'datfix' made the change 'Set DATE-BEG to '2022-06-03T06:35:24.645' from MJD-BEG.
Set DATE-AVG to '2022-06-03T06:52:40.747' from MJD-AVG.
Set DATE-END to '2022-06-03T07:09:56.881' from MJD-END'. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   -82.803316 from OBSGEO-[XYZ].
Set OBSGEO-B to   -31.519446 from OBSGEO-[XYZ].
Set OBSGEO-H to 1653612642.314 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]
WARNING: Input data contains invalid values (NaNs or infs), which were automatically masked. [photutils.background.background_2d]

real	0m4.530s
user	0m4.305s
sys	0m1.333s
WARNING: FITSFixedWarning: 'datfix' made the change 'Set DATE-BEG to '2022-06-03T07:13:31.618' from MJD-BEG.
Set DATE-AVG to '2022-06-03T07:30:47.704' from MJD-AVG.
Set DATE-END to '2022-06-03T07:48:03.790' from MJD-END'. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   -82.778744 from OBSGEO-[XYZ].
Set OBSGEO-B to   -31.536287 from OBSGEO-[XYZ].
Set OBSGEO-H to 1653867491.040 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]
WARNING: Input data contains invalid values (NaNs or infs), which were automatically masked. [photutils.background.background_2d]

real	0m4.235s
user	0m4.199s
sys	0m1.286s
WARNING: FITSFixedWarning: 'datfix' made the change 'Set DATE-BEG to '2022-06-03T05:36:53.693' from MJD-BEG.
Set DATE-AVG to '2022-06-03T06:04:03.008' from MJD-AVG.
Set DATE-END to '2022-06-03T06:31:17.715' from MJD-END'. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   -82.825006 from OBSGEO-[XYZ].
Set OBSGEO-B to   -31.504583 from OBSGEO-[XYZ].
Set OBSGEO-H to 1653387953.977 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]
WARNING: Input data contains invalid values (NaNs or infs), which were automatically masked. [photutils.background.background_2d]

real	0m4.209s
user	0m4.161s
sys	0m1.305s
#+end_example

Now all the MIRI filters

#+header: :prologue exec 2>&1 :epilogue :
#+begin_src sh :dir data :results verbatim
  for FN in f770w f1130w f1280w f1800w; do
      time python ../scripts/findbg-local.py wr124-jwst-miri-2022-${FN}.fits
  done
#+end_src

#+RESULTS:
#+begin_example
WARNING: FITSFixedWarning: 'datfix' made the change 'Set DATE-BEG to '2022-06-10T19:13:15.243' from MJD-BEG.
Set DATE-AVG to '2022-06-10T20:42:59.464' from MJD-AVG.
Set DATE-END to '2022-06-10T22:12:50.973' from MJD-END'. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   -79.020464 from OBSGEO-[XYZ].
Set OBSGEO-B to   -34.077472 from OBSGEO-[XYZ].
Set OBSGEO-H to 1694854319.412 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]
WARNING: Input data contains invalid values (NaNs or infs), which were automatically masked. [photutils.background.background_2d]

real	0m15.767s
user	0m2.877s
sys	0m1.215s
WARNING: FITSFixedWarning: 'datfix' made the change 'Set DATE-BEG to '2022-06-10T19:49:39.240' from MJD-BEG.
Set DATE-AVG to '2022-06-10T21:19:22.082' from MJD-AVG.
Set DATE-END to '2022-06-10T22:49:09.403' from MJD-END'. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   -79.011629 from OBSGEO-[XYZ].
Set OBSGEO-B to   -34.083187 from OBSGEO-[XYZ].
Set OBSGEO-H to 1694947246.087 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]
WARNING: Input data contains invalid values (NaNs or infs), which were automatically masked. [photutils.background.background_2d]

real	0m2.169s
user	0m2.684s
sys	0m1.022s
WARNING: FITSFixedWarning: 'datfix' made the change 'Set DATE-BEG to '2022-06-10T20:24:51.110' from MJD-BEG.
Set DATE-AVG to '2022-06-10T21:54:36.204' from MJD-AVG.
Set DATE-END to '2022-06-10T23:24:18.521' from MJD-END'. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   -79.005847 from OBSGEO-[XYZ].
Set OBSGEO-B to   -34.086925 from OBSGEO-[XYZ].
Set OBSGEO-H to 1695008013.869 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]
WARNING: Input data contains invalid values (NaNs or infs), which were automatically masked. [photutils.background.background_2d]

real	0m2.488s
user	0m2.729s
sys	0m1.099s
WARNING: FITSFixedWarning: 'datfix' made the change 'Set DATE-BEG to '2022-06-10T21:00:27.917' from MJD-BEG.
Set DATE-AVG to '2022-06-10T22:30:14.762' from MJD-AVG.
Set DATE-END to '2022-06-11T00:00:03.671' from MJD-END'. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   -78.991877 from OBSGEO-[XYZ].
Set OBSGEO-B to   -34.095956 from OBSGEO-[XYZ].
Set OBSGEO-H to 1695154734.210 from OBSGEO-[XYZ]'. [astropy.wcs.wcs]
WARNING: Input data contains invalid values (NaNs or infs), which were automatically masked. [photutils.background.background_2d]

real	0m2.273s
user	0m2.819s
sys	0m0.995s
#+end_example


****** Source finding in JWST images

#+begin_src sh :dir data :results verbatim
  for f in wr124-jwst-nircam-2022-f????_BGSUB.fits; do
      python ../scripts/find-sources.py $f 5.0 30.0
  done
#+end_src

#+RESULTS:
#+begin_example
Source list saved to wr124-jwst-nircam-2022-f090w_BGSUB-sources-fwhm5.0-thresh30.ecsv
Region file saved to wr124-jwst-nircam-2022-f090w_BGSUB-sources-fwhm5.0-thresh30.reg
Source list saved to wr124-jwst-nircam-2022-f150w_BGSUB-sources-fwhm5.0-thresh30.ecsv
Region file saved to wr124-jwst-nircam-2022-f150w_BGSUB-sources-fwhm5.0-thresh30.reg
Source list saved to wr124-jwst-nircam-2022-f210m_BGSUB-sources-fwhm5.0-thresh30.ecsv
Region file saved to wr124-jwst-nircam-2022-f210m_BGSUB-sources-fwhm5.0-thresh30.reg
Source list saved to wr124-jwst-nircam-2022-f335m_BGSUB-sources-fwhm5.0-thresh30.ecsv
Region file saved to wr124-jwst-nircam-2022-f335m_BGSUB-sources-fwhm5.0-thresh30.reg
Source list saved to wr124-jwst-nircam-2022-f444w_BGSUB-sources-fwhm5.0-thresh30.ecsv
Region file saved to wr124-jwst-nircam-2022-f444w_BGSUB-sources-fwhm5.0-thresh30.reg
Source list saved to wr124-jwst-nircam-2022-f470n_BGSUB-sources-fwhm5.0-thresh30.ecsv
Region file saved to wr124-jwst-nircam-2022-f470n_BGSUB-sources-fwhm5.0-thresh30.reg
#+end_example

#+begin_src sh :dir data :results verbatim
  for f in wr124-jwst-miri-2022-f*w_BGSUB.fits; do
      python ../scripts/find-sources.py $f 5.0 30.0
  done
#+end_src

#+RESULTS:
: Source list saved to wr124-jwst-miri-2022-f1130w_BGSUB-sources-fwhm5.0-thresh30.ecsv
: Region file saved to wr124-jwst-miri-2022-f1130w_BGSUB-sources-fwhm5.0-thresh30.reg
: Source list saved to wr124-jwst-miri-2022-f1280w_BGSUB-sources-fwhm5.0-thresh30.ecsv
: Region file saved to wr124-jwst-miri-2022-f1280w_BGSUB-sources-fwhm5.0-thresh30.reg
: Source list saved to wr124-jwst-miri-2022-f1800w_BGSUB-sources-fwhm5.0-thresh30.ecsv
: Region file saved to wr124-jwst-miri-2022-f1800w_BGSUB-sources-fwhm5.0-thresh30.reg
: Source list saved to wr124-jwst-miri-2022-f770w_BGSUB-sources-fwhm5.0-thresh30.ecsv
: Region file saved to wr124-jwst-miri-2022-f770w_BGSUB-sources-fwhm5.0-thresh30.reg

****** Source matching and aligning of JWST images

******* Match JWST f090w to HST 1999 continuum and Ha

First the continuum. We put in a guess of 1 arcsec offset in RA, since that looks more or less right. 
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-hst-1997-f675w_BGSUB wr124-jwst-nircam-2022-f090w_BGSUB \
         fwhm2.0-thresh1 fwhm5.0-thresh30 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 1.0 --guess-pa 270.0 \
         --object-name wr124 --combo-prefix wr124-hst-1997-f675w-TO-jwst-2022-f090w
#+end_src

#+RESULTS:
: Statistics based on 246 coincident sources
: Mean displacement in RA: -1026.00 +/- 4.16 marcsec
: Mean displacement in Dec: 73.80 +/- 3.48 marcsec
: Median displacement in RA: -1036.43 +/- 1.92 marcsec
: Median displacement in Dec: 76.99 +/- 2.70 marcsec

So this works really well. We have a lot of coincident stars and their offsets are nice and tightly distributed. 

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-hst-1997-f675w-TO-jwst-2022-f090w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-1997-f675w-TO-jwst-2022-f090w-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-hst-1997-f675w-TO-jwst-2022-f090w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-1997-f675w-TO-jwst-2022-f090w-OFFSETS-CORR.pdf]]

#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-hst-1997-f656n_BGSUB wr124-jwst-nircam-2022-f090w_BGSUB \
         fwhm2.0-thresh1 fwhm5.0-thresh30 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 1.0 --guess-pa 270.0 \
         --object-name wr124 --combo-prefix wr124-hst-1997-f656n-TO-jwst-2022-f090w
#+end_src

#+RESULTS:
: Statistics based on 12 coincident sources
: Mean displacement in RA: -885.80 +/- 52.51 marcsec
: Mean displacement in Dec: 34.33 +/- 22.94 marcsec
: Median displacement in RA: -780.75 +/- 15.10 marcsec
: Median displacement in Dec: 51.26 +/- 14.64 marcsec

This is less satisfactory because it found very few coincident sources, so it would be better to use the continuum to tie these together
#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-hst-1997-f656n-TO-jwst-2022-f090w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-1997-f656n-TO-jwst-2022-f090w-OFFSETS.pdf]]

******* Match between NIRCAM JWST filters

******** f090w to f150w
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-nircam-2022-f090w_BGSUB wr124-jwst-nircam-2022-f150w_BGSUB \
         fwhm5.0-thresh30 fwhm5.0-thresh30 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 0.0 --guess-pa 0.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f090w-TO-f150w
#+end_src

#+RESULTS:
: Statistics based on 409 coincident sources
: Mean displacement in RA: 0.96 +/- 2.44 marcsec
: Mean displacement in Dec: 1.74 +/- 2.66 marcsec
: Median displacement in RA: -0.38 +/- 0.16 marcsec
: Median displacement in Dec: -3.99 +/- 0.16 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f090w-TO-f150w-OFFSETS.ecsv --max-sep 30
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f090w-TO-f150w-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f090w-TO-f150w-OFFSETS.ecsv --max-sep 30
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f090w-TO-f150w-OFFSETS-CORR.pdf]]

******** f150w to f210m
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-nircam-2022-f150w_BGSUB wr124-jwst-nircam-2022-f210m_BGSUB \
         fwhm5.0-thresh30 fwhm5.0-thresh30 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 0.0 --guess-pa 0.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f150w-TO-f210m
#+end_src

#+RESULTS:
: Statistics based on 2143 coincident sources
: Mean displacement in RA: 1.56 +/- 0.66 marcsec
: Mean displacement in Dec: -3.19 +/- 0.75 marcsec
: Median displacement in RA: 3.01 +/- 0.02 marcsec
: Median displacement in Dec: -2.20 +/- 0.03 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f150w-TO-f210m-OFFSETS.ecsv --max-sep 30
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f150w-TO-f210m-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f150w-TO-f210m-OFFSETS.ecsv --max-sep 10
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f150w-TO-f210m-OFFSETS-CORR.pdf]]

- This is finally showing a distortion effect:
  - we see systematic variation of dRA with RA and dDEC with DEC
  - but it is very small!
  - only 5 mas per 100 arcsec
  - But on the other hand, it is comparable to the median shift

******** f210m to f335m
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-nircam-2022-f210m_BGSUB wr124-jwst-nircam-2022-f335m_BGSUB \
         fwhm5.0-thresh30 fwhm5.0-thresh30 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 0.0 --guess-pa 0.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f210m-TO-f335m
#+end_src

#+RESULTS:
: Statistics based on 838 coincident sources
: Mean displacement in RA: 7.31 +/- 1.61 marcsec
: Mean displacement in Dec: -33.10 +/- 1.74 marcsec
: Median displacement in RA: 0.51 +/- 0.13 marcsec
: Median displacement in Dec: -43.65 +/- 0.09 marcsec

This has a much larger displacement in Dec than between the other NIRCAM filters,  which we can  see in the RGB image

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f210m-TO-f335m-OFFSETS.ecsv --max-sep 30
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f210m-TO-f335m-OFFSETS.pdf]]

There is a strange bifurcation in  dRA distributions between the small radii and the large radii
#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f210m-TO-f335m-OFFSETS.ecsv --max-sep 10
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f210m-TO-f335m-OFFSETS-CORR.pdf]]

There is a slight trend in displacement as a function of position,   but this time it is even apparent in the cross terms: e.g., dRA vs DEC

This could be explained as a combination of expansion and rotation


******** f335m to f444w
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-nircam-2022-f335m_BGSUB wr124-jwst-nircam-2022-f444w_BGSUB \
         fwhm5.0-thresh30 fwhm5.0-thresh30 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 0.0 --guess-pa 0.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f335m-TO-f444w
#+end_src

#+RESULTS:
: Statistics based on 466 coincident sources
: Mean displacement in RA: 4.51 +/- 0.92 marcsec
: Mean displacement in Dec: 5.15 +/- 1.35 marcsec
: Median displacement in RA: 3.78 +/- 0.08 marcsec
: Median displacement in Dec: 5.22 +/- 0.06 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f335m-TO-f444w-OFFSETS.ecsv --max-sep 30
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f335m-TO-f444w-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f335m-TO-f444w-OFFSETS.ecsv --max-sep 10
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f335m-TO-f444w-OFFSETS-CORR.pdf]]

******** f444w to f470n
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-nircam-2022-f444w_BGSUB wr124-jwst-nircam-2022-f470n_BGSUB \
         fwhm5.0-thresh30 fwhm5.0-thresh30 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 0.0 --guess-pa 0.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f444w-TO-f470n
#+end_src

#+RESULTS:
: Statistics based on 391 coincident sources
: Mean displacement in RA: -4.98 +/- 1.17 marcsec
: Mean displacement in Dec: -14.62 +/- 1.51 marcsec
: Median displacement in RA: -6.57 +/- 0.87 marcsec
: Median displacement in Dec: -12.74 +/- 1.04 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f444w-TO-f470n-OFFSETS.ecsv --max-sep 100
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f444w-TO-f470n-OFFSETS.pdf]]

This has more dispersion and fewer sources than the other pairs we have done, but it still seems to give a reliable shift

The stars at smaller radii seem to have less dispersion in their displacements

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f444w-TO-f470n-OFFSETS.ecsv --max-sep 100
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f444w-TO-f470n-OFFSETS-CORR.pdf]]

We get *very* strong linear correlation of dRA with RA and dDec with Dec, which suggests something strange might be going on

******* Match NIRCAM to MIRI
- Try this over the shortest gap: f444w to f770w
- We know that MIRI is well matched to HST, so is offset about 1 arcsec in RA from NIRCAM

#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-nircam-2022-f444w_BGSUB wr124-jwst-miri-2022-f770w_BGSUB \
         fwhm5.0-thresh30 fwhm5.0-thresh30 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 1.0 --guess-pa 90.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f444w-TO-f770w   
#+end_src

#+RESULTS:
: Statistics based on 42 coincident sources
: Mean displacement in RA: 1042.90 +/- 3.25 marcsec
: Mean displacement in Dec: 2.18 +/- 3.56 marcsec
: Median displacement in RA: 1042.42 +/- 4.65 marcsec
: Median displacement in Dec: 1.62 +/- 3.96 marcsec

This seems to have worked, but there are a disturbingly small number of sources

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f444w-TO-f770w-OFFSETS.ecsv --max-sep 100
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f444w-TO-f770w-OFFSETS.pdf]]

So the claimed accuracy is about 5 mas, but the distribution of offsets is not very gaussian, with sub clusters separated by about 20 mas, so that would be a better estimate of accuracy

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f444w-TO-f770w-OFFSETS.ecsv --max-sep 100
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f444w-TO-f770w-OFFSETS-CORR.pdf]]

This shows a clear linear trend in the off-diagonal pairs, with opposite slopes, which is consistent with rotation

******* Match between MIRI filters

******** f770w to f1130w
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-miri-2022-f770w_BGSUB wr124-jwst-miri-2022-f1130w_BGSUB \
         fwhm5.0-thresh30 fwhm5.0-thresh30 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 0.0 --guess-pa 0.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f770w-TO-f1130w   
#+end_src

#+RESULTS:
: Statistics based on 87 coincident sources
: Mean displacement in RA: 1.17 +/- 2.46 marcsec
: Mean displacement in Dec: -14.48 +/- 3.28 marcsec
: Median displacement in RA: -1.34 +/- 2.26 marcsec
: Median displacement in Dec: -13.62 +/- 1.80 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f770w-TO-f1130w-OFFSETS.ecsv --max-sep 100
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f770w-TO-f1130w-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f770w-TO-f1130w-OFFSETS.ecsv --max-sep 100
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f770w-TO-f1130w-OFFSETS-CORR.pdf]]

Sources are very concentrated towards center in RA, but not in Dec

******** f1130w to f1280w
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-miri-2022-f1130w_BGSUB wr124-jwst-miri-2022-f1280w_BGSUB \
         fwhm5.0-thresh30 fwhm5.0-thresh30 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 0.0 --guess-pa 0.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f1130w-TO-f1280w   
#+end_src

#+RESULTS:
: Statistics based on 92 coincident sources
: Mean displacement in RA: -3.51 +/- 7.95 marcsec
: Mean displacement in Dec: 9.03 +/- 9.86 marcsec
: Median displacement in RA: 1.97 +/- 5.84 marcsec
: Median displacement in Dec: 12.66 +/- 6.91 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f1130w-TO-f1280w-OFFSETS.ecsv --max-sep 300
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f1130w-TO-f1280w-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f1130w-TO-f1280w-OFFSETS.ecsv --max-sep 300
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f1130w-TO-f1280w-OFFSETS-CORR.pdf]]

The close-in stars have a much larger dispersion than the farther out ones. I have no idea why this is the case

******** f1280w to f1800w
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-miri-2022-f1280w_BGSUB wr124-jwst-miri-2022-f1800w_BGSUB \
         fwhm5.0-thresh30 fwhm5.0-thresh30 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 0.0 --guess-pa 0.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f1280w-TO-f1800w
#+end_src

#+RESULTS:
: Statistics based on 96 coincident sources
: Mean displacement in RA: -4.58 +/- 7.36 marcsec
: Mean displacement in Dec: 0.69 +/- 7.84 marcsec
: Median displacement in RA: -5.01 +/- 6.39 marcsec
: Median displacement in Dec: -15.72 +/- 6.82 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f1280w-TO-f1800w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f1280w-TO-f1800w-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f1280w-TO-f1800w-OFFSETS.ecsv  --alpha 0.3
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f1280w-TO-f1800w-OFFSETS-CORR.pdf]]



****** Apply shifts to JWST images
***** TODO Align to GAIA frame
- Maybe this would be a good idea


Get all the GAIA sources in the field with a radius of three arcmin

#+begin_src sh :dir data :results verbatim
  python ../scripts/get-gaia-catalog.py \
         --object-name wr124 \
         --search-radius-arcsec 180.0 
#+end_src

#+RESULTS:
: INFO: Query finished. [astroquery.utils.tap.core]
****** HST f675w continuum to GAIA
:PROPERTIES:
:ID:       CD08DF32-308B-4F9C-A6C5-A76C52482495
:END:
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-hst-1997-f675w_BGSUB gaia \
         fwhm2.0-thresh1 wr124 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 0.0 --guess-pa 0.0 \
         --object-name wr124 --combo-prefix wr124-hst-1997-f675w-TO-gaia
#+end_src

#+RESULTS:
: Statistics based on 339 coincident sources
: Mean displacement in RA: -6.61 +/- 1.90 marcsec
: Mean displacement in Dec: -133.67 +/- 2.47 marcsec
: Median displacement in RA: -8.79 +/- 1.51 marcsec
: Median displacement in Dec: -136.61 +/- 2.04 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-hst-1997-f675w-TO-gaia-OFFSETS.ecsv --max-sep 200
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-1997-f675w-TO-gaia-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-hst-1997-f675w-TO-gaia-OFFSETS.ecsv --max-sep 200 --alpha 0.3
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-1997-f675w-TO-gaia-OFFSETS-CORR.pdf]]

Slight evidence for a rotation of the HST frame with respect to GAIA
****** HST f555w to Gaia
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-hst-1997-f555w_BGSUB gaia \
         fwhm2.0-thresh10 wr124 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.15 \
         --guess-offset 0.1 --guess-pa 180.0 \
         --object-name wr124 --combo-prefix wr124-hst-1997-f555w-TO-gaia
#+end_src

#+RESULTS:
: Statistics based on 93 coincident sources
: Mean displacement in RA: -15.87 +/- 3.22 marcsec
: Mean displacement in Dec: -81.64 +/- 4.57 marcsec
: Median displacement in RA: -20.04 +/- 2.94 marcsec
: Median displacement in Dec: -84.09 +/- 4.66 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-hst-1997-f555w-TO-gaia-OFFSETS.ecsv 
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-1997-f555w-TO-gaia-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-hst-1997-f555w-TO-gaia-OFFSETS.ecsv 
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-1997-f555w-TO-gaia-OFFSETS-CORR.pdf]]

****** HST f656n Ha first epoch to Gaia
:PROPERTIES:
:ID:       F646740A-848E-4F5F-B333-5B931D06C3E4
:END:
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-hst-1997-f656n_BGSUB gaia \
         fwhm2.0-thresh1 wr124 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 0.0 --guess-pa 0.0 \
         --object-name wr124 --combo-prefix wr124-hst-1997-f656n-TO-gaia
#+end_src

#+RESULTS:
: Statistics based on 43 coincident sources
: Mean displacement in RA: 11.58 +/- 5.43 marcsec
: Mean displacement in Dec: -79.62 +/- 8.62 marcsec
: Median displacement in RA: 4.13 +/- 5.43 marcsec
: Median displacement in Dec: -89.65 +/- 8.12 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-hst-1997-f656n-TO-gaia-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-1997-f656n-TO-gaia-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-hst-1997-f656n-TO-gaia-OFFSETS.ecsv --max-sep 200 --alpha 0.3
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-1997-f656n-TO-gaia-OFFSETS-CORR.pdf]]

****** HST f656n Ha second epoch to Gaia
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-hst-2008-f656n_BGSUB gaia \
         fwhm2.0-thresh1 wr124 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 0.0 --guess-pa 0.0 \
         --object-name wr124 --combo-prefix wr124-hst-2008-f656n-TO-gaia
#+end_src

#+RESULTS:
: Statistics based on 36 coincident sources
: Mean displacement in RA: 16.90 +/- 3.51 marcsec
: Mean displacement in Dec: -56.02 +/- 4.90 marcsec
: Median displacement in RA: 14.64 +/- 3.48 marcsec
: Median displacement in Dec: -55.21 +/- 4.64 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-hst-2008-f656n-TO-gaia-OFFSETS.ecsv --max-sep 100
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-2008-f656n-TO-gaia-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-hst-2008-f656n-TO-gaia-OFFSETS.ecsv --max-sep 200 --alpha 0.3
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-hst-2008-f656n-TO-gaia-OFFSETS-CORR.pdf]]

****** NIRCAM f090w to GAIA
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-nircam-2022-f090w_BGSUB gaia \
         fwhm5.0-thresh30 wr124 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 1.0 --guess-pa 90.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f090w-TO-gaia
#+end_src

#+RESULTS:
: Statistics based on 122 coincident sources
: Mean displacement in RA: 1021.35 +/- 7.18 marcsec
: Mean displacement in Dec: -197.42 +/- 5.28 marcsec
: Median displacement in RA: 1022.59 +/- 1.41 marcsec
: Median displacement in Dec: -210.59 +/- 1.69 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f090w-TO-gaia-OFFSETS.ecsv --max-sep 100
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f090w-TO-gaia-OFFSETS.pdf]]


#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f090w-TO-gaia-OFFSETS.ecsv --max-sep 100 --alpha 0.3
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f090w-TO-gaia-OFFSETS-CORR.pdf]]

This shows clear signs of rotation

****** NIRCAM f090w to HST f675w
The GAIA alignments may be insufficiently precise, so we want to directly tie together NIRCAM and HST

Note that we reduce the max separation to 200 mas to avoid outliers (chosen by eye, based on experiments with larger values up to 500).  This yield fewer coincident sources,  but the results are more robust.

#+begin_src sh :dir data :results verbatim
    python ../scripts/find-offset.py \
           wr124-jwst-nircam-2022-f090w_BGSUB \
           wr124-hst-1997-f675w_BGSUB \
           fwhm5.0-thresh30 fwhm2.0-thresh10 \
           --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.2 \
           --guess-offset 1.0 --guess-pa 90.0 \
           --object-name wr124 --combo-prefix wr124-jwst-2022-f090w-TO-hst-1997-f675w
#+end_src

#+RESULTS:
: Statistics based on 24 coincident sources
: Mean displacement in RA: 1020.60 +/- 14.32 marcsec
: Mean displacement in Dec: -60.63 +/- 9.70 marcsec
: Median displacement in RA: 1022.06 +/- 8.72 marcsec
: Median displacement in Dec: -56.72 +/- 7.19 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f090w-TO-hst-1997-f675w-OFFSETS.ecsv 
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f090w-TO-hst-1997-f675w-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f090w-TO-hst-1997-f675w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f090w-TO-hst-1997-f675w-OFFSETS-CORR.pdf]]

So this has bigger error bars than the Gaia alignment, which makes me think that we do want to go through GAIA after all for tying these together

Note that both HST and NIRCAM have similar rotations to the GAIA frame, so there is no significant relative rotation between the two instruments.

****** NIRCAM f150w to GAIA
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-nircam-2022-f150w_BGSUB gaia \
         fwhm5.0-thresh30 wr124 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 1.0 --guess-pa 90.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f150w-TO-gaia
#+end_src

#+RESULTS:
: Statistics based on 109 coincident sources
: Mean displacement in RA: 1039.02 +/- 7.61 marcsec
: Mean displacement in Dec: -132.01 +/- 13.57 marcsec
: Median displacement in RA: 1027.28 +/- 1.64 marcsec
: Median displacement in Dec: -196.53 +/- 2.72 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f150w-TO-gaia-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f150w-TO-gaia-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f150w-TO-gaia-OFFSETS.ecsv --alpha 0.3
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f150w-TO-gaia-OFFSETS-CORR.pdf]]

This one has the least satisfactory robust fit. I am going to try and improve it

****** NIRCAM f210m to GAIA
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-nircam-2022-f210m_BGSUB gaia \
         fwhm5.0-thresh30 wr124 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 1.0 --guess-pa 90.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f210m-TO-gaia
#+end_src

#+RESULTS:
: Statistics based on 404 coincident sources
: Mean displacement in RA: 1021.37 +/- 2.96 marcsec
: Mean displacement in Dec: -185.43 +/- 3.81 marcsec
: Median displacement in RA: 1022.15 +/- 0.83 marcsec
: Median displacement in Dec: -204.17 +/- 1.02 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f210m-TO-gaia-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f210m-TO-gaia-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f210m-TO-gaia-OFFSETS.ecsv --alpha 0.3
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f210m-TO-gaia-OFFSETS-CORR.pdf]]


****** NIRCAM f335m to GAIA
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-nircam-2022-f335m_BGSUB gaia \
         fwhm5.0-thresh30 wr124 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 1.0 --guess-pa 90.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f335m-TO-gaia
#+end_src

#+RESULTS:
: Statistics based on 345 coincident sources
: Mean displacement in RA: 1023.05 +/- 0.97 marcsec
: Mean displacement in Dec: -159.17 +/- 2.13 marcsec
: Median displacement in RA: 1022.76 +/- 0.81 marcsec
: Median displacement in Dec: -162.58 +/- 1.00 marcsec


#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f335m-TO-gaia-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f335m-TO-gaia-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f335m-TO-gaia-OFFSETS.ecsv --alpha 0.3
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f335m-TO-gaia-OFFSETS-CORR.pdf]]


****** NIRCAM f444w to GAIA
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-nircam-2022-f444w_BGSUB gaia \
         fwhm5.0-thresh30 wr124 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 1.0 --guess-pa 90.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f444w-TO-gaia
#+end_src

#+RESULTS:
: Statistics based on 353 coincident sources
: Mean displacement in RA: 1018.60 +/- 0.91 marcsec
: Mean displacement in Dec: -166.55 +/- 1.57 marcsec
: Median displacement in RA: 1018.37 +/- 0.83 marcsec
: Median displacement in Dec: -167.85 +/- 0.97 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f444w-TO-gaia-OFFSETS.ecsv --max-sep 100
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f444w-TO-gaia-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f444w-TO-gaia-OFFSETS.ecsv --alpha 0.3
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f444w-TO-gaia-OFFSETS-CORR.pdf]]


****** NIRCAM f470n to GAIA
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-nircam-2022-f470n_BGSUB gaia \
         fwhm5.0-thresh30 wr124 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 1.0 --guess-pa 90.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f470n-TO-gaia
#+end_src

#+RESULTS:
: Statistics based on 352 coincident sources
: Mean displacement in RA: 1024.28 +/- 1.25 marcsec
: Mean displacement in Dec: -153.83 +/- 1.83 marcsec
: Median displacement in RA: 1023.46 +/- 1.36 marcsec
: Median displacement in Dec: -153.83 +/- 1.62 marcsec


#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f470n-TO-gaia-OFFSETS.ecsv --max-sep 100
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f470n-TO-gaia-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f470n-TO-gaia-OFFSETS.ecsv --alpha 0.3
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f470n-TO-gaia-OFFSETS-CORR.pdf]]

This is the first one to show a scale as well as a rotation.  

****** MIRI f770w to GAIA

#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-miri-2022-f770w_BGSUB gaia \
         fwhm5.0-thresh30 wr124 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 0.0 --guess-pa 0.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f770w-TO-gaia
#+end_src

#+RESULTS:
: Statistics based on 73 coincident sources
: Mean displacement in RA: -21.87 +/- 2.04 marcsec
: Mean displacement in Dec: -164.40 +/- 5.73 marcsec
: Median displacement in RA: -22.98 +/- 1.83 marcsec
: Median displacement in Dec: -171.72 +/- 2.19 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f770w-TO-gaia-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f770w-TO-gaia-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f770w-TO-gaia-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f770w-TO-gaia-OFFSETS-CORR.pdf]]

****** MIRI f1130w to GAIA

#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-miri-2022-f1130w_BGSUB gaia \
         fwhm5.0-thresh30 wr124 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 0.0 --guess-pa 0.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f1130w-TO-gaia
#+end_src

#+RESULTS:
: Statistics based on 26 coincident sources
: Mean displacement in RA: -13.80 +/- 9.89 marcsec
: Mean displacement in Dec: -148.69 +/- 12.14 marcsec
: Median displacement in RA: -23.48 +/- 5.43 marcsec
: Median displacement in Dec: -159.56 +/- 4.36 marcsec


#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f1130w-TO-gaia-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f1130w-TO-gaia-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f1130w-TO-gaia-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f1130w-TO-gaia-OFFSETS-CORR.pdf]]



****** MIRI f1280w to GAIA

#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-miri-2022-f1280w_BGSUB gaia \
         fwhm5.0-thresh30 wr124 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 0.0 --guess-pa 0.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f1280w-TO-gaia
#+end_src

#+RESULTS:
: Statistics based on 15 coincident sources
: Mean displacement in RA: -31.01 +/- 5.26 marcsec
: Mean displacement in Dec: -171.02 +/- 5.89 marcsec
: Median displacement in RA: -32.11 +/- 7.57 marcsec
: Median displacement in Dec: -172.41 +/- 7.16 marcsec


#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f1280w-TO-gaia-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f1280w-TO-gaia-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f1280w-TO-gaia-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f1280w-TO-gaia-OFFSETS-CORR.pdf]]


****** MIRI f1800w to GAIA

#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-jwst-miri-2022-f1800w_BGSUB gaia \
         fwhm5.0-thresh30 wr124 \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --guess-offset 0.0 --guess-pa 0.0 \
         --object-name wr124 --combo-prefix wr124-jwst-2022-f1800w-TO-gaia
#+end_src

#+RESULTS:
: Statistics based on 8 coincident sources
: Mean displacement in RA: -12.12 +/- 12.13 marcsec
: Mean displacement in Dec: -151.68 +/- 6.52 marcsec
: Median displacement in RA: -14.95 +/- 15.55 marcsec
: Median displacement in Dec: -147.72 +/- 7.18 marcsec


#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-jwst-2022-f1800w-TO-gaia-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f1800w-TO-gaia-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-jwst-2022-f1800w-TO-gaia-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-jwst-2022-f1800w-TO-gaia-OFFSETS-CORR.pdf]]
***** Test the yaml numpy dump
#+begin_src sh :dir scripts :results verbatim
  python npyaml.py
#+end_src

#+RESULTS:
#+begin_example
ndarray:
- 1
- 2
- 3

scalar int ndarray: 1

scalar float ndarray: 1.0

np.int64: 1

np.float64: 1.0

#+end_example
***** DONE Details of the robust fits
CLOSED: [2023-09-27 Wed 19:30]
- I am using the default method to start with, which works well in most cases, but in the f150w filter it is too affected by outliers
- So I am going to try a weighting function that is more aggressive in winnowing the outliers
- Default weighting function is ~HuberT~, which has a very gentle fall off (1/x)
- These are called M-estimators and the best documentation is file:///Users/will/Library/Application%20Support/Dash/User%20Contributed/statsmodels/statsmodels%200.14.docset/Contents/Resources/Documents/examples/notebooks/generated/robust_models_1.html
- I will try with trimmed mean instead, which is the most drastic. Basically the same as sigma-clipping
  - I will use ~c = 3~, which is number of sigma to clip (where sigma is actually from MAD)
- This seems to work very well.  All the fits look more credible now. In all cases except f150w the changes were very small
- 
***** DONE Apply the correction terms
CLOSED: [2023-10-19 Thu 09:57]
- We now write out the offset and linear correction matrix to a yaml file
- We are getting inconsistent results from applying them though, which I need to investigate
  - [2023-10-13 Fri] I think I have found part of the problem at least. The reference pixel does not correspond to the central star, so any adjustment to the CD matrix will also produce a net shift
  - The other thing I want to do is to use only the rotation and scale components
- [2023-10-19 Thu] This now gives good enough results, so I will not attempt to refine it further
    
****** HST 1997 continuum to GAIA
First, just the offset
#+begin_src sh :dir data :results verbatim
    python ../scripts/apply-alignment.py \
           wr124-hst-1997-f675w \
           wr124-hst-1997-f675w-TO-gaia \
           --output-suffix SHIFT-GAIA \
           --offset-only
#+end_src

#+RESULTS:
: Offset: [  -8.08987622 -135.45859063] marcsec
: Scale: 1.000000, Rotation: 0.000000

Second, the full transform
#+begin_src sh :dir data :results verbatim
  python ../scripts/apply-alignment.py \
         wr124-hst-1997-f675w \
         wr124-hst-1997-f675w-TO-gaia \
         --output-suffix ALIGN-GAIA 
#+end_src

#+RESULTS:
: Offset: [  -8.08987622 -135.45859063] marcsec
: Rotation -0.000202 (significant at -3.159 sigma)
: Scale: 1.000000, Rotation: -0.000202

****** HST 1997 green continuum to Gaia
#+begin_src sh :dir data :results verbatim
  python ../scripts/apply-alignment.py \
         wr124-hst-1997-f555w \
         wr124-hst-1997-f555w-TO-gaia \
         --output-suffix ALIGN-GAIA 
#+end_src

#+RESULTS:
: Offset: [-15.3002092  -81.39261515] marcsec
: Rotation -0.000222 (significant at -1.506 sigma)
: Scale: 1.000000, Rotation: -0.000222

****** HST 1997 Ha to continuum
Shift only 
#+begin_src sh :dir data :results verbatim
  python ../scripts/apply-alignment.py \
         wr124-hst-1997-f656n \
         wr124-hst-1997-f656n-TO-f675w \
         --output-suffix SHIFT-f675w \
         --offset-only
#+end_src

#+RESULTS:
: Offset: [ 7.22065939 53.37060761] marcsec
: Scale: 1.000000, Rotation: 0.000000

Second, the full transform
#+begin_src sh :dir data :results verbatim
  python ../scripts/apply-alignment.py \
         wr124-hst-1997-f656n \
         wr124-hst-1997-f656n-TO-f675w \
         --output-suffix ALIGN-f675w 
#+end_src

#+RESULTS:
: Offset: [ 7.22065939 53.37060761] marcsec
: Scale 1.000214 (significant at 2.965 sigma)
: Scale: 1.000214, Rotation: 0.000000

****** HST 1997 green to red continuum
Shift only 
#+begin_src sh :dir data :results verbatim
  python ../scripts/apply-alignment.py \
         wr124-hst-1997-f555w \
         wr124-hst-1997-f555w-TO-f675w \
         --output-suffix SHIFT-f675w \
         --offset-only
#+end_src

#+RESULTS:
: Offset: [-12.55697143  57.66793642] marcsec
: Scale: 1.000000, Rotation: 0.000000

#+begin_src sh :dir data :results verbatim
  python ../scripts/apply-alignment.py \
         wr124-hst-1997-f555w \
         wr124-hst-1997-f555w-TO-f675w \
         --output-suffix ALIGN-f675w 
#+end_src

#+RESULTS:
: Offset: [-12.55697143  57.66793642] marcsec
: WARNING: On-axis shear -0.000042 (significant at -1.042 sigma)
: Scale: 1.000000, Rotation: 0.000000

****** HST 1997 Ha to GAIA
Shift only 
#+begin_src sh :dir data :results verbatim
  python ../scripts/apply-alignment.py \
         wr124-hst-1997-f656n \
         wr124-hst-1997-f656n-TO-gaia \
         --output-suffix SHIFT-GAIA \
         --offset-only
#+end_src

#+RESULTS:
: Offset: [ 11.5484252  -83.23478082] marcsec
: Scale: 1.000000, Rotation: 0.000000

Full transform
#+begin_src sh :dir data :results verbatim
  python ../scripts/apply-alignment.py \
         wr124-hst-1997-f656n \
         wr124-hst-1997-f656n-TO-gaia \
         --output-suffix ALIGN-GAIA 
#+end_src

#+RESULTS:
: Offset: [ 11.5484252  -83.23478082] marcsec
: Rotation -0.000312 (significant at -1.295 sigma)
: Scale: 1.000000, Rotation: -0.000312

****** HST 2008 Ha to GAIA
#+begin_src sh :dir data :results verbatim
  python ../scripts/apply-alignment.py \
         wr124-hst-2008-f656n \
         wr124-hst-2008-f656n-TO-gaia \
         --output-suffix SHIFT-GAIA \
         --offset-only
#+end_src

#+RESULTS:
: Offset: [ 16.21792661 -57.217935  ] marcsec
: Scale: 1.000000, Rotation: 0.000000

#+begin_src sh :dir data :results verbatim
  python ../scripts/apply-alignment.py \
         wr124-hst-2008-f656n \
         wr124-hst-2008-f656n-TO-gaia \
         --output-suffix ALIGN-GAIA 
#+end_src

#+RESULTS:
: Offset: [ 16.21792661 -57.217935  ] marcsec
: Rotation -0.000390 (significant at -2.977 sigma)
: Scale: 1.000000, Rotation: -0.000390

****** HST 2008 Ha to 1997 continuum
Shift only
#+begin_src sh :dir data :results verbatim
  python ../scripts/apply-alignment.py \
         wr124-hst-2008-f656n \
         wr124-hst-2008-f656n-TO-1997-f675w \
         --output-suffix SHIFT-1997-f675w \
         --offset-only
#+end_src

#+RESULTS:
: Offset: [ 9.60345428 77.42534219] marcsec
: Scale: 1.000000, Rotation: 0.000000

****** NIRCAM f090w to HST continuum
Shift only

#+begin_src sh :dir data :results verbatim
  python ../scripts/apply-alignment.py \
         wr124-jwst-nircam-2022-f090w \
         wr124-jwst-2022-f090w-TO-hst-1997-f675w \
         --output-suffix SHIFT-HST \
         --offset-only
#+end_src

#+RESULTS:
: Offset: [1030.29826074  -65.68302727] marcsec
: Scale: 1.000000, Rotation: 0.000000

Also scale and rotate
#+begin_src sh :dir data :results verbatim
  python ../scripts/apply-alignment.py \
         wr124-jwst-nircam-2022-f090w \
         wr124-jwst-2022-f090w-TO-hst-1997-f675w \
         --output-suffix ALIGN-HST 
#+end_src

#+RESULTS:
: Offset: [1030.29826074  -65.68302727] marcsec
: Scale: 1.000000, Rotation: 0.000000

****** NIRCAM to GAIA


#+begin_src sh :dir data :results verbatim
  python ../scripts/apply-alignment.py \
         wr124-jwst-nircam-2022-f090w \
         wr124-jwst-2022-f090w-TO-gaia \
         --output-suffix SHIFT-GAIA \
         --offset-only
#+end_src

#+RESULTS:
: Offset: [1024.71753151 -212.89214037] marcsec
: Scale: 1.000000, Rotation: 0.000000

Full transform
#+begin_src sh :dir data :results verbatim
  for F in f090w f150w f210m f335m f444w f470n; do
    echo "NIRCAM $F to GAIA"
    python ../scripts/apply-alignment.py \
           wr124-jwst-nircam-2022-$F \
           wr124-jwst-2022-$F-TO-gaia \
           --output-suffix ALIGN-GAIA
    echo
  done
#+end_src

#+RESULTS:
#+begin_example
NIRCAM f090w to GAIA
Offset: [1024.71753151 -212.89214037] marcsec
WARNING: Off-axis shear 0.000046 (significant at 1.238 sigma)
Rotation -0.000269 (significant at -7.321 sigma)
Scale: 1.000000, Rotation: -0.000269

NIRCAM f150w to GAIA
Offset: [1025.13267886 -205.03170231] marcsec
Rotation -0.000265 (significant at -6.584 sigma)
Scale: 1.000000, Rotation: -0.000265

NIRCAM f210m to GAIA
Offset: [1022.21858083 -206.1106554 ] marcsec
WARNING: Off-axis shear 0.000038 (significant at 1.771 sigma)
Rotation -0.000262 (significant at -12.311 sigma)
Scale 1.000053 (significant at 1.752 sigma)
Scale: 1.000053, Rotation: -0.000262

NIRCAM f335m to GAIA
Offset: [1022.70303814 -162.6647966 ] marcsec
WARNING: Off-axis shear 0.000027 (significant at 1.300 sigma)
Rotation -0.000294 (significant at -13.964 sigma)
Scale: 1.000000, Rotation: -0.000294

NIRCAM f444w to GAIA
Offset: [1018.61605194 -167.59920456] marcsec
WARNING: Off-axis shear 0.000028 (significant at 1.316 sigma)
Rotation -0.000313 (significant at -14.496 sigma)
Scale: 1.000000, Rotation: -0.000313

NIRCAM f470n to GAIA
Offset: [1024.1702356 -154.4711154] marcsec
Rotation -0.000299 (significant at -7.479 sigma)
Scale 1.000423 (significant at 12.992 sigma)
Scale: 1.000423, Rotation: -0.000299

#+end_example


****** MIRI to GAIA
#+begin_src sh :dir data :results verbatim
  for F in f770w f1130w f1280w f1800w; do
    echo "MIRI $F to GAIA"
    python ../scripts/apply-alignment.py \
           wr124-jwst-miri-2022-$F \
           wr124-jwst-2022-$F-TO-gaia \
           --output-suffix ALIGN-GAIA
    echo
  done
#+end_src

#+RESULTS:
#+begin_example
MIRI f770w to GAIA
Offset: [ -21.59359324 -170.80839271] marcsec
Rotation 0.000149 (significant at 2.346 sigma)
Scale 1.000093 (significant at 1.321 sigma)
Scale: 1.000093, Rotation: 0.000149

MIRI f1130w to GAIA
Offset: [ -22.73882763 -156.49597159] marcsec
WARNING: Off-axis shear -0.000275 (significant at -1.856 sigma)
Scale 0.999808 (significant at -1.158 sigma)
Scale: 0.999808, Rotation: 0.000000

MIRI f1280w to GAIA
Offset: [ -30.36850347 -170.03723244] marcsec
WARNING: Off-axis shear -0.000271 (significant at -1.344 sigma)
Scale 0.999719 (significant at -1.314 sigma)
Scale: 0.999719, Rotation: 0.000000

MIRI f1800w to GAIA
Offset: [ -13.75302628 -153.81436994] marcsec
Scale: 1.000000, Rotation: 0.000000

#+end_example

***** Test the results of applying the alignment
- We have corrected the WCS of different images to give alignment to the GAIA frame
- But when we look at these in DS9, they do no seem to be that well aligned with one another
- So I want a quantitative measure of the alignment
- We can re-run the ~plot-offsets.py~ and the ~plot-offsets-corr.py~ scripts for the relative displacements to see how well the images are aligned
  - But we need to have a list of point sources for the gaia-aligned image
  - However, the source lists are in pixel coordinates, so we can just reuse the original ones that we already did for each observation
  - We just need to make a symbolic link so that the program can find them


****** Test case: HST 1997 Ha and continuum
We do this first because it is using the CD matrix, which should be more straightforward

******* Summary of results
- The shift in DEC worked OK, but the RA shift seems to be overcompensated
  - Is this because of the cos delta term?
  - delta is 17 deg, so cos delta is 0.96, which should not make a big difference
  - It seems to be just due to inaccuracy in f656n-TO-gaia matching
- But the expansion/rotation has not
  - There was a slight expansion in the original f656n-to-f675w of about 2e-4
    - No significant rotation or skew
  - In the GAIA-aligned version it is still there with an additional on-axis skew
- Compare with the individual HST-to-GAIA alignments
  - [[id:F646740A-848E-4F5F-B333-5B931D06C3E4][HST f656n Ha first epoch to Gaia]]
  - [[id:CD08DF32-308B-4F9C-A6C5-A76C52482495][HST f675w continuum to GAIA]]
- Lesson seems to be that we should only use the best filter of a given camera for the GAIA matching
  - And other filters should be done relatively
  - Also, we should not construct the CD matrix directly, but rather extract a scale and rotation
  - And apply them only if they are significant
  - And the skew terms should never be applied (although reported if they seem significant)
    - One reason for this is that I suspect that DS9 does not use the skew terms in the WCS when displaying the image
- With the shifts only we get a good mutual alignment between f555w, f675w, and f656n
  - It eliminates rainbow patterns that we saw in RGB image without correction


******* Relative vs absolute alignments
- The relative alignment f656n-TO-f675w gives
  - offset, mas:
    + 7 +/- 2
    + 52 +/- 2
  - (1 - scale), ppm : 210 +/- 50
  - rotation, tan\theta, ppm: -30 +/- 65 so no significant rotation
  - on-axis skew, ppm: 80 +/- 50, marginally significant
  - off-axis skew, ppm: 50 +/- 65, not significant
- The absolute alignment f656n-TO-gaia gives
  - offset, mas:
    + 11 +/- 5
    + -83 +/- 8
  - (1 - scale), ppm : 180 +/- 180
  - rotation, tan\theta, ppm: -310 +/- 150
  - on-axis skew, ppm: -120 +/- 180
  - off-axis skew, ppm: 10 +/- 150, insignificant
- The absolute alignment f675w-TO-gaia gives
  - offset, mas:
    + -8 +/- 2
    + -135 +/- 2
  - (1 - scale), ppm : -9 +/- 50, insignificant
  - rotation, tan\theta, ppm: -202 +/- 40 
  - on-axis skew, ppm: 46 +/- 50, insignificant
  - off-axis skew, ppm: -59 +/- 65, insignificant


******** Accuracy of round tripping
- With the shifts only we have
  - Round trip shifts
     | From   | To     | RA        | Dec        |
     |--------+--------+-----------+------------|
     | f656n  | Gaia   | 11 +/- 5  | -83 +/- 8  |
     | f675w  | Gaia   | -8 +/- 2  | -135 +/- 2 |
     |--------+--------+-----------+------------|
     | f656n* | f675w* | 19 +/- 5. | 52 +/- 8.  |
     | f656n  | f675w  | 7 +/- 2   | 52 +/- 2   |
     |--------+--------+-----------+------------|
     | f656n  | f656n  | 12 +/- 5. | 0 +/- 8.   |
     #+TBLFM: @4$3..@4$4=@-2 - @-1 ;f0::@6$3..@6$4=@-2 - @-1 ;f0
  - Starred values are indirect via gaia: f656n -> gaia -> f675w
  - Final row is the round trip f656n -> gaia -> f675w -> f656n
  - We have a 2.5 sigma discrepancy in the RA

******* Symbolic links to give source lists for gaia-aligned images
#+begin_src sh :dir data :results verbatim
  ln -sf wr124-hst-1997-f656n_BGSUB-sources-fwhm2.0-thresh1.ecsv \
     wr124-hst-1997-f656n-ALIGN-GAIA-sources-LINK.ecsv
  ln -sf wr124-hst-1997-f675w_BGSUB-sources-fwhm2.0-thresh10.ecsv \
     wr124-hst-1997-f675w-ALIGN-GAIA-sources-LINK.ecsv
#+end_src

#+begin_src sh :dir data :results verbatim
  ln -sf wr124-hst-1997-f656n_BGSUB-sources-fwhm2.0-thresh1.ecsv \
     wr124-hst-1997-f656n-SHIFT-GAIA-sources-LINK.ecsv
  ln -sf wr124-hst-1997-f675w_BGSUB-sources-fwhm2.0-thresh10.ecsv \
     wr124-hst-1997-f675w-SHIFT-GAIA-sources-LINK.ecsv
#+end_src

#+RESULTS:

******* Re-run the relative offsets plots
Using the Gaia-aligned images
#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-hst-1997-f656n-ALIGN-GAIA wr124-hst-1997-f675w-ALIGN-GAIA \
         LINK LINK \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --object-name wr124 --combo-prefix wr124-ALIGN-GAIA-hst-1997-f656n-TO-f675w
#+end_src

#+RESULTS:
: Statistics based on 43 coincident sources
: Mean displacement in RA: -12.15 +/- 2.38 marcsec
: Mean displacement in Dec: 1.08 +/- 2.60 marcsec
: Median displacement in RA: -12.61 +/- 2.41 marcsec
: Median displacement in Dec: 0.91 +/- 2.98 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-ALIGN-GAIA-hst-1997-f656n-TO-f675w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-ALIGN-GAIA-hst-1997-f656n-TO-f675w-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-ALIGN-GAIA-hst-1997-f656n-TO-f675w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-ALIGN-GAIA-hst-1997-f656n-TO-f675w-OFFSETS-CORR.pdf]]

Repeat for the shift-only images

#+begin_src sh :dir data :results verbatim
  python ../scripts/find-offset.py \
         wr124-hst-1997-f656n-SHIFT-GAIA wr124-hst-1997-f675w-SHIFT-GAIA \
         LINK LINK \
         --minimum-radius-arcsec 1.0 --maximum-separation-arcsec 0.3 \
         --object-name wr124 --combo-prefix wr124-SHIFT-GAIA-hst-1997-f656n-TO-f675w
#+end_src

#+RESULTS:
: Statistics based on 43 coincident sources
: Mean displacement in RA: -11.85 +/- 2.29 marcsec
: Mean displacement in Dec: 1.23 +/- 2.47 marcsec
: Median displacement in RA: -11.29 +/- 2.55 marcsec
: Median displacement in Dec: 1.50 +/- 2.74 marcsec

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets.py wr124-SHIFT-GAIA-hst-1997-f656n-TO-f675w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-SHIFT-GAIA-hst-1997-f656n-TO-f675w-OFFSETS.pdf]]

#+begin_src sh :dir data :results file
  python ../scripts/plot-offsets-corr.py wr124-SHIFT-GAIA-hst-1997-f656n-TO-f675w-OFFSETS.ecsv
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/wr124-SHIFT-GAIA-hst-1997-f656n-TO-f675w-OFFSETS-CORR.pdf]]

***** Compare with Alejandro results
- CSV file with shifts from Alejandro
  - [[file:correction_coor_2.csv]]
***** Summary of shifts between images
- We will make a provisional table with all the shifts, plus comments on any patterns in the residuals
****** Relative shifts between adjacent images


|                | From   | To     | d RA              | d Dec           |    N |    pix | Comments                      |
|----------------+--------+--------+-------------------+-----------------+------+--------+-------------------------------|
| HST -> JWST    | f675w  | f090w  | -1036.43 +/- 1.92 | 76.99 +/- 2.70  |  246 | 100/31 |                               |
|----------------+--------+--------+-------------------+-----------------+------+--------+-------------------------------|
| NIRCAM short   | f090w  | f150w  | -0.38 +/- 0.16    | -3.99 +/- 0.16  |  409 |     31 |                               |
|                | f150w  | f210m  | 3.01 +/- 0.02     | -2.20 +/- 0.03  | 2143 |     31 | Linear contraction 30 ppm     |
| short -> long  | f210m  | f335m  | 0.51 +/- 0.13     | -43.65 +/- 0.09 |  838 |  31/63 | Expansion and rotation 70 ppm |
| NIRCAM long    | f335m  | f444w  | 3.78 +/- 0.08     | 5.22 +/- 0.06   |  466 |     63 | Rotation 30 ppm = 6 arcsec    |
|                | f444w  | f470n  | -6.57 +/- 0.87    | -12.74 +/- 1.04 |  391 |     63 | Strong contraction 400 ppm    |
|----------------+--------+--------+-------------------+-----------------+------+--------+-------------------------------|
| NIRCAM -> MIRI | f444w  | f770w  | 1042.42 +/- 4.65  | 1.62 +/- 3.96   |   42 | 63/111 | Rotation 500 ppm = 100 arcsec |
|----------------+--------+--------+-------------------+-----------------+------+--------+-------------------------------|
| MIRI           | f770w  | f1130w | -1.34 +/- 2.26    | -13.62 +/- 1.80 |   87 |    111 |                               |
|                | f1130w | f1280w | 1.97 +/- 5.84     | 12.66 +/- 6.91  |   92 |    111 | High dispersion at small r    |
|                | f1280w | f1800w | -5.01 +/- 6.39    | -15.72 +/- 6.82 |   96 |    111 | Ditto                         |
|----------------+--------+--------+-------------------+-----------------+------+--------+-------------------------------|
****** Absolute shifts to GAIA frame
All are to Gaia

|              | From   | d RA             | d Dec            |   N | pix | Comments |
|--------------+--------+------------------+------------------+-----+-----+----------|
| HST -> Gaia  | f675w  | -8.79 +/- 1.51   | -136.61 +/- 2.04 | 339 | 100 | rotation |
| 1997         | f656n  | 4.13 +/- 5.43    | -89.65 +/- 8.12  |  43 | 100 |          |
| 2008         | f656n  | 14.64 +/- 3.48   | -55.21 +/- 4.64  |  36 | 100 |          |
|--------------+--------+------------------+------------------+-----+-----+----------|
| NIRCAM short | f090w  | 1022.59 +/- 1.41 | -210.59 +/- 1.69 | 122 |  31 | rotation |
|              | f150w  | 1027.28 +/- 1.64 | -196.53 +/- 2.72 | 109 |  31 |          |
|              | f210m  | 1022.15 +/- 0.83 | -204.17 +/- 1.02 | 404 |  31 |          |
|--------------+--------+------------------+------------------+-----+-----+----------|
| NIRCAM long  | f335m  | 1022.76 +/- 0.81 | -162.58 +/- 1.00 | 345 |  63 |          |
|              | f444w  | 1018.37 +/- 0.83 | -167.85 +/- 0.97 | 353 |  63 |          |
|              | f470n  | 1023.46 +/- 1.36 | -153.83 +/- 1.62 | 352 |  63 |          |
|--------------+--------+------------------+------------------+-----+-----+----------|
| MIRI         | f770w  | -22.98 +/- 1.83  | -171.72 +/- 2.19 |  73 | 111 |          |
|              | f1130w | -23.48 +/- 5.43  | -159.56 +/- 4.36 |  26 | 111 |          |
|              | f1280w | -32.11 +/- 7.57  | -172.41 +/- 7.16 |  15 | 111 |          |
|              | f1800w | -14.95 +/- 15.55 | -147.72 +/- 7.18 |   8 | 111 |          |
|--------------+--------+------------------+------------------+-----+-----+----------|

***** Other work on JWST astrometry
- This is mainly by Johannes Sahlmann
****** Lessons learned from Sahlmann 2017 JWST-STScI-005492
- JWST TECHNICAL REPORT
- Astrometric accuracy of the JWST calibration field catalog examined with the first Gaia data release
- They are comparing HST-ACS and GAIA astrometry for the JWST calibration field in the LMC
- They fit highest degree d polynomials to the displacements
  - They describe these by the "mode" k = 2 (d + 1)
  - k = 2, d = 0 is a constant offset (2 parameters)
  - k = 4, d = 1 adds linear transformations: scale, rotation, and skew (6 additional parameters)
  - k = 6, d = 2 adds quadratic terms (12 additional parameters)
  - etc ...
- They find that they get "significant" improvement with k=8 (d=3) over k=6
  - However, this is just the statistical significance (p < 0.0027, which I think is 3 sigma)
  - It doesn't actually reduce the RMS of the residuals by very much over k=4 (from 1.835 mas to 1.778 mas in X, and from 2.513 mas to 2.369 mas in Y)
  - So, I think that *for our purposes we can stick with k=4 (linear transformations)* because we are not really interested in effects below 1 mas
  - Apparently the residual RMS is dominated by proper motions in this case, consistent with 50 km/s at distance of LMC over the 8.5 year baseline
- It turns out that the "HST convention" is that "distortions" are the corrections other than global offset, global rotation, and global scale (which it calls "calibrations")
  - So we will probably not need to bother with these /distortions/ unless a shear turns out to be important
  - But other conventions count the global scale as one of the "distortions"
- For their comparison, they find global scale and global rotation maximum offsets of order 5 mas, and skew maximum offsets of order 0.8 mas
- The linear terms can be decomposed into four components, which can be expressed in terms of the partial derivatives x_x, x_y, y_x, y_y (called b, c, d, e, f in the report)
  - global scale = sqrt(x_x y_y - x_y y_x)
  - global rotation: tan \theta = (x_y - y_x) / (x_x + y_y)
  - on-axis skew (different scales in X and Y) = 0.5 (x_x - y_y)
  - off-axis skew (non-perpendicularity of X and Y axes) = 0.5 (x_y + y_x)
- Note that these partial derivatives are of the "evaluation frame" coordinates with respect to the "reference frame" coordinates, which correspond to the second (TO) and first (FROM) image respectively in our case
  - So they are x_x = d x_2 / d x_1, x_y = d x_2 / d y_1, y_x = d y_2 / d x_1, y_y = d y_2 / d y_1
  - Our residual graphs are plotting
    - x_2 - x_1 versus x_1
    - x_2 - x_1 versus y_1, etc
  - So the slopes of our residual graphs are
    - D_xx = d x_2 / d x_1 - d x_1 / d x_1 = x_x - 1
    - D_xy = d x_2 / d y_1 - d x_1 / d y_1 = x_y (because x_1 and y_1 are independent)
    - D_yx = y_x
    - D_yy = y_y - 1
  - So we can put 
    - global scale: A = sqrt((D_xx + 1) (D_yy + 1) - D_xy D_yx)
      - Then to first order in D_xx, D_yy, D_xy, D_yx, we have ...
      - ... (A - 1) = 0.5 (D_xx + D_yy)
    - global rotation: tan \theta = (D_xy - D_yx) / (2 + D_xx + D_yy)
      - tan \theta = (D_xy - D_yx) / 2 A
      - First order ... tan \theta = 0.5 (D_xy - D_yx)
    - on-axis skew: B = 0.5 (D_xx - D_yy)
    - off-axis skew: C = 0.5 (D_xy + D_yx)
      
****** Follow-up report Sahlmann 2019 JWST-STScI-006828
- Does a similar study of HAWK-I catalog instead of HST-ACS
****** Third report Sahlmann 2020 JWST-STScI-007082
- Applies the same ideas to relative alignment between JWST instruments
- Uses FGS1, FGS2, and NIRISS (which are all parts of the same instrument)
- Finds lateral alignment offsets of 1 to 10 milliarcsec
- Finds orientation offsets of 3 to 6 arcsec (tan \theta less than 3e-5)
- Finds distortion terms (scale, skew) of order 1e-5
****** pystortion
- Abstract
  : pystortion provides support for distortion measurements in astronomical imagers. It includes classes to support fitting of bivariate polynomials of arbitrary degree and helper functions for crossmatching catalogs. The crossmatching uses an iterative approach in which a two-dimensional distortion model is fit at every iteration and used to continuously refine the position of extracted sources.
- https://ascl.net/2206.004
- https://github.com/spacetelescope/pystortion
- This includes a crossmatch module for matching sky catalogs
  - It is a bit more sophisticated than mine since it is iterative and uses the distortion model to refine the positions of the sources
- There is not really any documentation, but there are extensive tests, so it should be easy to work out how to use it

***** Find and apply scale and rotation calibrations
- We can fit straight lines to the residuals to get the first order derivatives
- Then we can directly map those onto the FITS PC matrix for the rotation and CDELT for the scale (or CD matrix for both)

 
** Reprojection and calculation of ratios
- [2023-10-19 Thu] We will reproject the images onto an orthogonal ra-dec grid, since that will make things easier for using matplotlib
- Initial approach is to take small groups of similar filters, as we did for the rgb images
- 
*** [2023-10-22 Sun] Initial results of ratios
- The alignment seems very good for the JWST filters, but is still not good enough for HST
  - so I need to try again with tying the HST f675w to GAIA-aligned NIRCAM f090w, and then the other HST filters in a chain from there
- 

  

*** Make a folder to hold them all
#+begin_src sh :dir data :results verbatim
  mkdir -vp reproject
#+end_src

#+RESULTS:
: reproject

*** Reproject NIRCAM images

Test with just f090w first
#+begin_src sh :dir data :results verbatim
  for F in f090w; do
    echo "NIRCAM $F reproject"
    time python ../scripts/reproject-radec.py \
           wr124-jwst-nircam-2022-$F-ALIGN-GAIA \
           reproject/wr124-jwst-nircam-2022-$F-radec \
           --pixel-scale-arcsec 0.031 \
           --angular-size-arcmin 2.5
    echo
  done
#+end_src

#+RESULTS:
: NIRCAM f090w reproject
: 

Then do the rest
#+begin_src sh :dir data :results verbatim
  for F in f150w f210m f335m f444w f470n; do
    echo "NIRCAM $F reproject"
    time python ../scripts/reproject-radec.py \
           wr124-jwst-nircam-2022-$F-ALIGN-GAIA \
           reproject/wr124-jwst-nircam-2022-$F-radec \
           --pixel-scale-arcsec 0.031 \
           --angular-size-arcmin 2.5
    echo
  done
#+end_src

#+RESULTS:
#+begin_example
NIRCAM f150w reproject

NIRCAM f210m reproject

NIRCAM f335m reproject

NIRCAM f444w reproject

NIRCAM f470n reproject

#+end_example

*** Reproject MIRI images
#+begin_src sh :dir data :results verbatim
  for F in f770w f1130w f1280w f1800w; do
    echo "MIRI $F reproject"
    time python ../scripts/reproject-radec.py \
           wr124-jwst-miri-2022-$F-ALIGN-GAIA \
           reproject/wr124-jwst-miri-2022-$F-radec \
           --pixel-scale-arcsec 0.031 \
           --angular-size-arcmin 2.5
    echo
  done
#+end_src

#+RESULTS:
: MIRI f770w reproject
: 
: MIRI f1130w reproject
: 
: MIRI f1280w reproject
: 
: MIRI f1800w reproject
: 

*** Reproject HST images
#+begin_src sh :dir data :results verbatim
  for F in 2008-f656n; do
    echo "HST $F reproject"
    time python ../scripts/reproject-radec.py \
           wr124-hst-$F-ALIGN-GAIA \
           reproject/wr124-hst-$F-radec \
           --pixel-scale-arcsec 0.031 \
           --angular-size-arcmin 2.5
    echo
  done
#+end_src

#+RESULTS:
: HST 2008-f656n reproject
: 

#+begin_src sh :dir data :results verbatim
  for F in 1997-f555w 1997-f675w 1997-f656n; do
    echo "HST $F reproject"
    time python ../scripts/reproject-radec.py \
           wr124-hst-$F-ALIGN-GAIA \
           reproject/wr124-hst-$F-radec \
           --pixel-scale-arcsec 0.031 \
           --angular-size-arcmin 2.5
    echo
  done
#+end_src

#+RESULTS:
: HST 1997-f555w reproject
: 
: HST 1997-f675w reproject
: 
: HST 1997-f656n reproject
: 

*** Ratio of NIRCAM images

#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-jwst-nircam-2022-f470n-radec.fits \
         wr124-jwst-nircam-2022-f444w-radec.fits \
         ratio-f470n-f444w.fits \
         --bg-a 0.2 --bg-b 0.2
#+end_src

#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-jwst-nircam-2022-f444w-radec.fits \
         wr124-jwst-nircam-2022-f335m-radec.fits \
         ratio-f444w-f335m.fits \
         --bg-a 0.2 --bg-b 0.18
#+end_src

#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-jwst-nircam-2022-f335m-radec.fits \
         wr124-jwst-nircam-2022-f210m-radec.fits \
         ratio-f335m-f210m.fits \
         --bg-a 0.15 --bg-b 0.1
#+end_src

#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-jwst-nircam-2022-f210m-radec.fits \
         wr124-jwst-nircam-2022-f150w-radec.fits \
         ratio-f210m-f150w.fits \
         --bg-a 0.1 --bg-b 0.22
#+end_src

#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-jwst-nircam-2022-f150w-radec.fits \
         wr124-jwst-nircam-2022-f090w-radec.fits \
         ratio-f150w-f090w.fits \
         --bg-a 0.22 --bg-b 0.2
#+end_src

#+begin_src sh :dir data/reproject :results verbatim
  python ../../scripts/find-ratio.py --help
#+end_src

#+RESULTS:
#+begin_example
Usage: find-ratio.py [OPTIONS] FILE_A FILE_B OUTFILE

  Find the ratio A/B of two fits images after subtracting respective
  backgrounds

Arguments:
  FILE_A   [required]
  FILE_B   [required]
  OUTFILE  [required]

Options:
  --bg-a FLOAT          [default: 0]
  --bg-b FLOAT          [default: 0]
  --install-completion  Install completion for the current shell.
  --show-completion     Show completion for the current shell, to copy it or
                        customize the installation.

  --help                Show this message and exit.
#+end_example

*** Ratio of MIRI images
First do MIRI/NIRCAM
#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-jwst-miri-2022-f770w-radec.fits \
         wr124-jwst-nircam-2022-f444w-radec.fits \
         ratio-f770w-f444w.fits \
         --bg-a 7.0 --bg-b 0.2
#+end_src
Then interband of MIRI
#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-jwst-miri-2022-f1130w-radec.fits \
         wr124-jwst-miri-2022-f770w-radec.fits \
         ratio-f1130w-f770w.fits \
         --bg-a 23.0 --bg-b 7.0
#+end_src

#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-jwst-miri-2022-f1280w-radec.fits \
         wr124-jwst-miri-2022-f1130w-radec.fits \
         ratio-f1280w-f1130w.fits \
         --bg-a 26.0 --bg-b 23.0
#+end_src
#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-jwst-miri-2022-f1800w-radec.fits \
         wr124-jwst-miri-2022-f1280w-radec.fits \
         ratio-f1800w-f1280w.fits \
         --bg-a 95.0 --bg-b 26.0
#+end_src

*** Ratio of HST images

#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-hst-2008-f656n-radec.fits \
         wr124-hst-1997-f656n-radec.fits \
         ratio-f656n-2008-1997.fits \
         --bg-a 0.0 --bg-b 0.0
#+end_src

#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-hst-1997-f675w-radec.fits \
         wr124-hst-1997-f656n-radec.fits \
         ratio-f675w-f656n.fits \
         --bg-a -0.02 --bg-b -0.02
#+end_src

#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-hst-1997-f675w-radec.fits \
         wr124-hst-1997-f555w-radec.fits \
         ratio-f675w-f555w.fits \
         --bg-a -0.02 --bg-b -0.05
#+end_src

#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-jwst-nircam-2022-f150w-radec.fits \
         wr124-hst-2008-f656n-radec.fits \
         ratio-f150w-f656n.fits \
         --bg-a 0.2 --bg-b -0.06
#+end_src

#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-jwst-nircam-2022-f090w-radec.fits \
         wr124-hst-2008-f656n-radec.fits \
         ratio-f090w-f656n.fits \
         --bg-a 0.22 --bg-b -0.06
#+end_src

#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-jwst-nircam-2022-f210m-radec.fits \
         wr124-hst-2008-f656n-radec.fits \
         ratio-f210m-f656n.fits \
         --bg-a 0.1 --bg-b -0.06
#+end_src

#+begin_src sh :dir data/reproject :results silent
  python ../../scripts/find-ratio.py \
         wr124-jwst-nircam-2022-f150w-radec.fits \
         wr124-hst-1997-f675w-radec.fits \
         ratio-f150w-f675w.fits \
         --bg-a 0.2 --bg-b -0.06
#+end_src

*** Take the minimum of the two HST Ha images
- The idea of this is to minimize the effects of the PSF in the region close to the star that we observe with the MIRI spectra


#+begin_src python :dir data/reproject :results output verbatim
  from astropy.io import fits
  import numpy as np

  hdu1 = fits.open("wr124-hst-1997-f656n-radec.fits")["SCI"]
  hdu2 = fits.open("wr124-hst-2008-f656n-radec.fits")["SCI"]

  newim = np.fmin(hdu1.data, hdu2.data)

  hdu1.data = newim
  hdu1.writeto("wr124-hst-MIN-f656n-radec.fits")

#+end_src

#+RESULTS:

** hst images
- [[file:MAST_wr124.json]] has a list  of the files that I have downloaded
  - These are the Level 3 products from the HLA of the WFPC2 observations, plus the Level 2 products from the FOC in the UV
  - On my laptop I have put the data files in file:/Users/will/Work/WR124-HST/

*** Available datasets
- I have got some images from HLA in the following filters
  - F656N
    - Two epochs
  - F555W
  - F675W
- They are badly contaminated by CRs, and I am not sure if these are the best observations or not
- It seems like the second F656N image I have is much better
  - Yes, this is the second epoch 2008-06
  - [2023-05-05 Fri] I am now using this image to mark the globules ass DS9 regions
- I also have some FOC images in the NUV, which appear to show nothing but the star
- Now I am downloading the original HST datasets (not the HLA ones)
  - They have the c1f extension, which means they may not have been drizzled

** Spitzer IRS spectra
- These are courtesy of Palmira



 
*** Apertures for IRS spectra
- [2023-10-24 Tue]
- I have converted the extraction area polygons into DS9 regions
  - using "composite" shape of 4 "line" shapes
  - e.g., from
    #+begin_example
      \FILENAME= 'wr124_SH_complete.tbl'
      \ COMMENT This file contains a spectral extraction created from
      \ COMMENT an IRS spectral mapping dataset.
      \ Extraction Area:
      \ # Poly: 19:11:30.463,+16:51:41.67 ; 19:11:30.306,+16:51:37.76
      \ #       19:11:31.397,+16:51:28.72 ; 19:11:31.554,+16:51:32.64
    #+end_example
    to
    #+begin_example
      # composite(19:11:30.7415,+16:51:36.500,4.8606623e-06) || composite=1 text={SH}
      line(19:11:30.463,+16:51:41.67,19:11:30.306,+16:51:37.76) || # line=0 0
      line(19:11:30.306,+16:51:37.76,19:11:31.397,+16:51:28.72) || # line=0 0
      line(19:11:31.397,+16:51:28.72,19:11:31.554,+16:51:32.64) || # line=0 0
      line(19:11:31.554,+16:51:32.64,19:11:30.463,+16:51:41.67) # line=0 0
    #+end_example
  - Then I converted them to DS9 boxes by overlaying the box by hand
    - [[file:m1-67-spitzer-irs-boxes.reg]]
  - Table of IRS extraction region sizes and positions
    |     | Length |  Width |  PA |   Area |
    |     | arcsec | arcsec | deg |    msr |
    |-----+--------+--------+-----+--------|
    | SH  |   18.1 |    4.6 | 210 | 0.0020 |
    | LH  |   31.3 |    8.8 | 305 | 0.0065 |
    | SL1 |  179.7 |   53.2 | 254 | 0.2247 |
    | SL2 |  215.8 |   54.3 | 254 | 0.2754 |
    | LL1 |  472.2 |   46.0 | 351 | 0.5105 |
    | LL2 |  437.7 |   44.9 | 350 | 0.4619 |
    #+TBLFM: $5=1e6 $2 $3 / (206265**2);f4
    - Note area is in milli-steradians (msr) because MJy/sr is Jy/msr
  - The apertures for the low-res spectra (LL: Long Low, SL: Short Low) are large and cover most of the nebula
    - About 50% of the full area (including halo)
    - but the LL and SL are orthogonal to one another, so they are not quite the same, which might explain the jump between them
  - The hi-res spectra (LH: Long High, SH: Short High) are much smaller
    - They cover small regions near the center of the nebula
    - This could explain why the surface brightnesses are higher

*** Plot the spectra
Test of throughput function

#+begin_src sh :dir scripts :results verbatim
  python filter_throughput.py
#+end_src

#+RESULTS:
: Transmission of f1800w
: [(<Quantity 16. micron>, 0.003939849542589399), (<Quantity 18. micron>, 0.4615843668830719), (<Quantity 22. micron>, 0.0)]

#+begin_src sh :dir data/spitzer-irs :results file
  python ../../scripts/plot-spitzer-irs.py
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/spitzer-irs/irs-spec.pdf]]

*** Identification of components

** JWST MIRI spectra

*** Extract 1d spectra from JWST cubes
#+begin_src sh :dir data/jwst-miri-mrs :results verbatim
  D=${HOME}/Work/WR124-JWST/MAST_2023-10-30T1155/JWST
  for chan in 1 2 3 4; do
      F=jw02730-c1001_t015_miri_ch${chan}-shortmediumlong
      echo chan $chan
      python ../../scripts/extract-spectra.py \
             ${D}/${F}/${F}_s3d.fits \
             ../../miri-spec-samples.reg \
             --save-prefix wr124-miri-spec-ch${chan} \
             --debug
      echo
  done
#+end_src

#+RESULTS:
#+begin_example
chan 1
Star
2D slice: (slice(21, 29, None), slice(20, 29, None))
Knot A
2D slice: (slice(27, 35, None), slice(12, 16, None))
BG A1
2D slice: (slice(23, 32, None), slice(6, 11, None))
BG A2
2D slice: (slice(31, 40, None), slice(17, 21, None))
Knot B
2D slice: (slice(42, 51, None), slice(8, 12, None))
BG B1
2D slice: (slice(36, 45, None), slice(3, 8, None))
BG B2
2D slice: (slice(42, 51, None), slice(15, 20, None))

chan 2
Star
2D slice: (slice(18, 25, None), slice(22, 28, None))
Knot A
2D slice: (slice(23, 30, None), slice(15, 19, None))
BG A1
2D slice: (slice(20, 27, None), slice(11, 15, None))
BG A2
2D slice: (slice(26, 33, None), slice(19, 23, None))
Knot B
2D slice: (slice(35, 42, None), slice(12, 16, None))
BG B1
2D slice: (slice(30, 37, None), slice(8, 12, None))
BG B2
2D slice: (slice(35, 42, None), slice(17, 21, None))

chan 3
Star
2D slice: (slice(24, 30, None), slice(25, 31, None))
Knot A
2D slice: (slice(28, 34, None), slice(19, 23, None))
BG A1
2D slice: (slice(25, 31, None), slice(16, 19, None))
BG A2
2D slice: (slice(31, 37, None), slice(23, 26, None))
Knot B
2D slice: (slice(38, 44, None), slice(17, 20, None))
BG B1
2D slice: (slice(34, 40, None), slice(14, 17, None))
BG B2
2D slice: (slice(38, 44, None), slice(21, 25, None))

chan 4
Star
2D slice: (slice(14, 18, None), slice(16, 20, None))
Knot A
2D slice: (slice(16, 20, None), slice(13, 15, None))
BG A1
2D slice: (slice(15, 18, None), slice(11, 13, None))
BG A2
2D slice: (slice(18, 21, None), slice(14, 17, None))
Knot B
2D slice: (slice(22, 26, None), slice(11, 13, None))
BG B1
2D slice: (slice(20, 23, None), slice(9, 12, None))
BG B2
2D slice: (slice(22, 26, None), slice(14, 16, None))

#+end_example

#+begin_src sh :dir data/jwst-miri-mrs :results verbatim
  python ../../scripts/extract-spectra.py --help
#+end_src

#+RESULTS:
#+begin_example
Usage: extract-spectra.py [OPTIONS] CUBE_FILE REGION_FILE

  Extract one-dimensional spectra from spectral cube

  Calculates one-dimensional spectra from line cube for extraction regions
  read from DS9 file.

Arguments:
  CUBE_FILE    [required]
  REGION_FILE  [required]

Options:
  --save-prefix TEXT
  --debug / --no-debug  [default: False]
  --install-completion  Install completion for the current shell.
  --show-completion     Show completion for the current shell, to copy it or
                        customize the installation.

  --help                Show this message and exit.
#+end_example

*** Plot JWST spectra for extracted regions
- Use a similar approach to with the Spitzer IRS spectra
- We can plot in 5 micron sections again and compare with the MIRI imaging pass bands
  - But then we have an additional section from 20 to 25 microns
- We take extraction regions for two knots A, and B
  - plus two BG regions for each
- Unfortunately, Knot B is outside the field of view of Channel 1


#+begin_src sh :dir data/jwst-miri-mrs :results file
  python ../../scripts/plot-spectra-miri.py
#+end_src

#+RESULTS:
[[file:/Users/will/Dropbox/globule-seminario/m1-67/data/jwst-miri-mrs/jwst-miri-mrs-spec.pdf]]

*** Median filter the cubes to better extract the narrow lines
- We can use the ~median_continuum.py~ script from the MUSE projects
- I plan to do a series of passes to isolate different features
  - Narrow filter (say 7 or 11 pixels) to remove the nebular lines
  - Intermediate filter (50 pixels or so) to remove the stellar lines
    - And this is applied to the "cont" given from the narrow filter
  - That should still leave the UIB features relatively unscathed
    - They would probably be best isolated by fitting a large scale polynomial

    - 

**** Copy original data cubes to the project folder and with less verbose names

#+begin_src sh :dir data/jwst-miri-mrs :results verbatim
  D=${HOME}/Work/WR124-JWST/MAST_2023-10-30T1155/JWST
  for chan in 1 2 3 4; do
      F=jw02730-c1001_t015_miri_ch${chan}-shortmediumlong
      cp -avf ${D}/${F}/${F}_s3d.fits wr124-miri-mrs-ch${chan}_s3d.fits
  done
#+end_src

#+RESULTS:
: /Users/will/Work/WR124-JWST/MAST_2023-10-30T1155/JWST/jw02730-c1001_t015_miri_ch1-shortmediumlong/jw02730-c1001_t015_miri_ch1-shortmediumlong_s3d.fits -> wr124-miri-mrs-ch1_s3d.fits
: /Users/will/Work/WR124-JWST/MAST_2023-10-30T1155/JWST/jw02730-c1001_t015_miri_ch2-shortmediumlong/jw02730-c1001_t015_miri_ch2-shortmediumlong_s3d.fits -> wr124-miri-mrs-ch2_s3d.fits
: /Users/will/Work/WR124-JWST/MAST_2023-10-30T1155/JWST/jw02730-c1001_t015_miri_ch3-shortmediumlong/jw02730-c1001_t015_miri_ch3-shortmediumlong_s3d.fits -> wr124-miri-mrs-ch3_s3d.fits
: /Users/will/Work/WR124-JWST/MAST_2023-10-30T1155/JWST/jw02730-c1001_t015_miri_ch4-shortmediumlong/jw02730-c1001_t015_miri_ch4-shortmediumlong_s3d.fits -> wr124-miri-mrs-ch4_s3d.fits

**** Command line help for new version of ~median_continuum.py~
#+begin_src sh :dir data/jwst-miri-mrs :results verbatim
  python ../../scripts/median_continuum.py --help
#+end_src

#+RESULTS:
#+begin_example
Usage: median_continuum.py [OPTIONS] WINDOW_SIZE CUBE_PATH

  Find and remove continuum from cube by median filtering

Arguments:
  WINDOW_SIZE  [required]
  CUBE_PATH    [required]

Options:
  --out-label TEXT             [default: median]
  --save-path PATH             [default: /Users/will/Dropbox/globule-
                               seminario/m1-67/data/jwst-miri-mrs]

  --two-pass / --no-two-pass   [default: False]
  --percentile FLOAT
  --first-window-size INTEGER  [default: 11]
  --shave-threshold FLOAT      [default: 0.1]
  --hdu-key TEXT               [default: SCI]
  --hdu-index INTEGER
  --install-completion         Install completion for the current shell.
  --show-completion            Show completion for the current shell, to copy
                               it or customize the installation.

  --help                       Show this message and exit.
#+end_example

**** Apply narrow filter for nebular emission lines
It turns out that these only take a few seconds to run
#+begin_src sh :dir data/jwst-miri-mrs :results output
  python ../../scripts/median_continuum.py 11 wr124-miri-mrs-ch1_s3d.fits --two-pass --shave-threshold 100
#+end_src

#+RESULTS:
: Saving median filtered cube to wr124-miri-mrs-ch1_s3d-median-cont-0011.fits
: Saving residual cube to wr124-miri-mrs-ch1_s3d-median-csub-0011.fits
: Saving ratio cube to wr124-miri-mrs-ch1_s3d-median-cdiv-0011.fits

Try a wider filter to better eliminate the [Ar II] line, which is super strong

#+begin_src sh :dir data/jwst-miri-mrs :results output
  python ../../scripts/median_continuum.py 21 wr124-miri-mrs-ch1_s3d.fits --no-two-pass 
#+end_src

#+RESULTS:
: Saving median filtered cube to wr124-miri-mrs-ch1_s3d-median-cont-0021.fits
: Saving residual cube to wr124-miri-mrs-ch1_s3d-median-csub-0021.fits
: Saving ratio cube to wr124-miri-mrs-ch1_s3d-median-cdiv-0021.fits


Turns out that 21 seems to be the best compromise, where the nebular lines are eliminated from the cont version.

#+begin_src sh :dir data/jwst-miri-mrs :results output
  python ../../scripts/median_continuum.py 21 wr124-miri-mrs-ch1_s3d.fits --two-pass --out-label med2pass
#+end_src

#+RESULTS:
: Saving median filtered cube to wr124-miri-mrs-ch1_s3d-med2pass-cont-0021.fits
: Saving residual cube to wr124-miri-mrs-ch1_s3d-med2pass-csub-0021.fits
: Saving ratio cube to wr124-miri-mrs-ch1_s3d-med2pass-cdiv-0021.fits

The two-pass version Does not make much difference, so we will not use it for now

#+begin_src sh :dir data/jwst-miri-mrs :results output
  python ../../scripts/median_continuum.py 21 wr124-miri-mrs-ch2_s3d.fits --no-two-pass 
#+end_src

#+RESULTS:
: Saving median filtered cube to wr124-miri-mrs-ch2_s3d-median-cont-0021.fits
: Saving residual cube to wr124-miri-mrs-ch2_s3d-median-csub-0021.fits
: Saving ratio cube to wr124-miri-mrs-ch2_s3d-median-cdiv-0021.fits

#+begin_src sh :dir data/jwst-miri-mrs :results output
  python ../../scripts/median_continuum.py 21 wr124-miri-mrs-ch3_s3d.fits --no-two-pass 
#+end_src

#+RESULTS:
: Saving median filtered cube to wr124-miri-mrs-ch3_s3d-median-cont-0021.fits
: Saving residual cube to wr124-miri-mrs-ch3_s3d-median-csub-0021.fits
: Saving ratio cube to wr124-miri-mrs-ch3_s3d-median-cdiv-0021.fits


Channel 4 seems to have wider pixels:
| Ch |   wav0 |  d wav |   d V |
|----+--------+--------+-------|
|  1 |    4.9 | 0.0008 |  49.0 |
|  2 |  7.511 | 0.0013 |  51.9 |
|  3 | 11.551 | 0.0025 |  64.9 |
|  4 |   17.7 |  0.006 | 101.7 |
#+TBLFM: $4=3e5 $3/$2;f1
So ch4 has twice as wide in velocity space at blue end of range (ch3 also has slightly wider pixels but it does not seem to matter)

So, we should use a narrower filter since with N=21 we are getting some stellar wind line in the ~csub~ profile

#+begin_src sh :dir data/jwst-miri-mrs :results output
  python ../../scripts/median_continuum.py 11 wr124-miri-mrs-ch4_s3d.fits --no-two-pass  
#+end_src

#+RESULTS:
: Saving median filtered cube to wr124-miri-mrs-ch4_s3d-median-cont-0011.fits
: Saving residual cube to wr124-miri-mrs-ch4_s3d-median-csub-0011.fits
: Saving ratio cube to wr124-miri-mrs-ch4_s3d-median-cdiv-0011.fits

**** Apply broader filter for the stellar lines
Apply this to the "cont" output of the N=21 filter (or N=11 for ch4)

***** Production runs of broad filter
- [2023-11-15 Wed] These are the ones I am using for the PSF construction
- I have been getting better results using a slightly wider filter, but with the 10th centile in place of the median
- This does better in the case of closely-spaced lines
  - It picks out the continuum in between them
- But it does badly in cases where there is an absorption feature
  - Since the absorption just gets spread out over the entire filter width

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/median_continuum.py 151 wr124-miri-mrs-ch1_s3d-median-cont-0021.fits --no-two-pass --percentile 10
#+end_src

#+RESULTS:
: Saving median filtered cube to wr124-miri-mrs-ch1_s3d-median-cont-0021-median-cont-0151.fits
: Saving residual cube to wr124-miri-mrs-ch1_s3d-median-cont-0021-median-csub-0151.fits
: Saving ratio cube to wr124-miri-mrs-ch1_s3d-median-cont-0021-median-cdiv-0151.fits

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/median_continuum.py 151 wr124-miri-mrs-ch2_s3d-median-cont-0021.fits --no-two-pass --percentile 10
#+end_src

#+RESULTS:
: Saving median filtered cube to wr124-miri-mrs-ch2_s3d-median-cont-0021-median-cont-0151.fits
: Saving residual cube to wr124-miri-mrs-ch2_s3d-median-cont-0021-median-csub-0151.fits
: Saving ratio cube to wr124-miri-mrs-ch2_s3d-median-cont-0021-median-cdiv-0151.fits

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/median_continuum.py 151 wr124-miri-mrs-ch3_s3d-median-cont-0021.fits --no-two-pass --percentile 10
#+end_src

#+RESULTS:
: Saving median filtered cube to wr124-miri-mrs-ch3_s3d-median-cont-0021-median-cont-0151.fits
: Saving residual cube to wr124-miri-mrs-ch3_s3d-median-cont-0021-median-csub-0151.fits
: Saving ratio cube to wr124-miri-mrs-ch3_s3d-median-cont-0021-median-cdiv-0151.fits

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/median_continuum.py 75 wr124-miri-mrs-ch4_s3d-median-cont-0011.fits --no-two-pass --percentile 10
#+end_src

#+RESULTS:
: Saving median filtered cube to wr124-miri-mrs-ch4_s3d-median-cont-0011-median-cont-0075.fits
: Saving residual cube to wr124-miri-mrs-ch4_s3d-median-cont-0011-median-csub-0075.fits
: Saving ratio cube to wr124-miri-mrs-ch4_s3d-median-cont-0011-median-cdiv-0075.fits

****** Older ones that are not so good
- Use N=81
#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/median_continuum.py 81 wr124-miri-mrs-ch1_s3d-median-cont-021.fits --two-pass --first-window-size 81 --shave-threshold 0.1
#+end_src

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/median_continuum.py 81 wr124-miri-mrs-ch2_s3d-median-cont-021.fits --two-pass --shave-threshold 10
#+end_src

#+RESULTS:

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/median_continuum.py 81 wr124-miri-mrs-ch3_s3d-median-cont-021.fits --two-pass --shave-threshold 10
#+end_src
#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/median_continuum.py 81 wr124-miri-mrs-ch4_s3d-median-cont-021.fits --two-pass --shave-threshold 10
#+end_src

#+RESULTS:

***** Initial tests of broad filter
Try N=101 to start with

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/median_continuum.py 401 wr124-miri-mrs-ch1_s3d-median-cont-021.fits --two-pass --shave-threshold 10
#+end_src

#+RESULTS:

- An issue that I found is that when the separation between two strong lines is of order the filter width, then we can get a bump in the "cont" profile *between* the lines, with a corresponding negative bump in the "csub" profile.  For ch4 this happens for N=101 and N=81.
- I tried to solve this by reducing N to 51, but that does not work since this means that we now get undersubtraction of all lines. So, I think N=81 is the optimum.
- The original problem is minor and can partially be solved by only taking positive part of the "csub" profile.
- The worst problems are in ch1 around 7.5 microns, where we have the convergence of
  - H I line
  - [Cl IV] line
  - PAH feature
- I have tried increasing to 201, but it did not help much
  - I will try 401 but I do not want to nuke the PAH features
  - YES, that works better, especially for the star spaxels
  - Although it does mean that some of the narrower PAH features gets filtered out of the final continuum
  - But hopefully that will not matter if we just these results to construct an average stellar spectrum

Now try 999, which is 0.8 microns in ch1 (/takes 40s to run/)
#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/median_continuum.py 999 wr124-miri-mrs-ch1_s3d-median-cont-021-median-cont-081.fits --two-pass --shave-threshold 1
#+end_src

#+RESULTS:

***** What if we were to apply the broad filter first?

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/median_continuum.py 301 wr124-miri-mrs-ch1_s3d.fits --no-two-pass --percentile 20
#+end_src

#+RESULTS:

This works OK, without any obvious artefacts, but the UIB profiles get split between the ~cont~ and the ~csub~ profiles

Try progressively larger filters

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/median_continuum.py 601 wr124-miri-mrs-ch1_s3d.fits --no-two-pass --percentile 20
#+end_src

#+RESULTS:

Try N=1001, for the star-subtracted cubes
#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  for i in 1 2 3 4; do
      time python ../../scripts/median_continuum.py 1001 \
             wr124-miri-mrs-ch${i}-nostar.fits --no-two-pass --percentile 20
  done
#+end_src

And N=501
#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  for i in 1 2 3; do
      time python ../../scripts/median_continuum.py 501 \
             wr124-miri-mrs-ch${i}-nostar.fits --no-two-pass --percentile 20
  done
  for i in 4; do
      time python ../../scripts/median_continuum.py 251 \
             wr124-miri-mrs-ch${i}-nostar.fits --no-two-pass --percentile 20
  done
#+end_src

#+RESULTS:
#+begin_example
Saving median filtered cube to wr124-miri-mrs-ch1-nostar-median-cont-0501.fits
Saving residual cube to wr124-miri-mrs-ch1-nostar-median-csub-0501.fits
Saving ratio cube to wr124-miri-mrs-ch1-nostar-median-cdiv-0501.fits
Saving median filtered cube to wr124-miri-mrs-ch2-nostar-median-cont-0501.fits
Saving residual cube to wr124-miri-mrs-ch2-nostar-median-csub-0501.fits
Saving ratio cube to wr124-miri-mrs-ch2-nostar-median-cdiv-0501.fits
Saving median filtered cube to wr124-miri-mrs-ch3-nostar-median-cont-0501.fits
Saving residual cube to wr124-miri-mrs-ch3-nostar-median-csub-0501.fits
Saving ratio cube to wr124-miri-mrs-ch3-nostar-median-cdiv-0501.fits
Saving median filtered cube to wr124-miri-mrs-ch4-nostar-median-cont-0251.fits
Saving residual cube to wr124-miri-mrs-ch4-nostar-median-csub-0251.fits
Saving ratio cube to wr124-miri-mrs-ch4-nostar-median-cdiv-0251.fits
#+end_example

***** And then apply the narrow one
#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  for i in 1 2 3; do
      python ../../scripts/median_continuum.py 21 \
             wr124-miri-mrs-ch${i}-nostar-median-csub-1001.fits --no-two-pass
  done

  for i in 4; do
      python ../../scripts/median_continuum.py 11 \
             wr124-miri-mrs-ch${i}-nostar-median-csub-1001.fits --no-two-pass
  done

#+end_src

#+RESULTS:
#+begin_example
Saving median filtered cube to wr124-miri-mrs-ch1-nostar-median-csub-1001-median-cont-0021.fits
Saving residual cube to wr124-miri-mrs-ch1-nostar-median-csub-1001-median-csub-0021.fits
Saving ratio cube to wr124-miri-mrs-ch1-nostar-median-csub-1001-median-cdiv-0021.fits
Saving median filtered cube to wr124-miri-mrs-ch2-nostar-median-csub-1001-median-cont-0021.fits
Saving residual cube to wr124-miri-mrs-ch2-nostar-median-csub-1001-median-csub-0021.fits
Saving ratio cube to wr124-miri-mrs-ch2-nostar-median-csub-1001-median-cdiv-0021.fits
Saving median filtered cube to wr124-miri-mrs-ch3-nostar-median-csub-1001-median-cont-0021.fits
Saving residual cube to wr124-miri-mrs-ch3-nostar-median-csub-1001-median-csub-0021.fits
Saving ratio cube to wr124-miri-mrs-ch3-nostar-median-csub-1001-median-cdiv-0021.fits
Saving median filtered cube to wr124-miri-mrs-ch4-nostar-median-csub-1001-median-cont-0011.fits
Saving residual cube to wr124-miri-mrs-ch4-nostar-median-csub-1001-median-csub-0011.fits
Saving ratio cube to wr124-miri-mrs-ch4-nostar-median-csub-1001-median-cdiv-0011.fits
#+end_example

These had some ringing around the strong lines, so I am going to see if two-pass will actually help like it is meant to

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  for i in 1 2 3; do
      python ../../scripts/median_continuum.py 21 \
             wr124-miri-mrs-ch${i}-nostar-median-csub-1001.fits --two-pass --first-window-size 21 --out-label med2pass
  done

  for i in 4; do
      python ../../scripts/median_continuum.py 11 \
             wr124-miri-mrs-ch${i}-nostar-median-csub-1001.fits --percentile 20 --two-pass --out-label med2pass
  done

#+end_src

#+RESULTS:
#+begin_example
Saving median filtered cube to wr124-miri-mrs-ch1-nostar-median-csub-1001-med2pass-cont-0021.fits
Saving residual cube to wr124-miri-mrs-ch1-nostar-median-csub-1001-med2pass-csub-0021.fits
Saving ratio cube to wr124-miri-mrs-ch1-nostar-median-csub-1001-med2pass-cdiv-0021.fits
Saving median filtered cube to wr124-miri-mrs-ch2-nostar-median-csub-1001-med2pass-cont-0021.fits
Saving residual cube to wr124-miri-mrs-ch2-nostar-median-csub-1001-med2pass-csub-0021.fits
Saving ratio cube to wr124-miri-mrs-ch2-nostar-median-csub-1001-med2pass-cdiv-0021.fits
Saving median filtered cube to wr124-miri-mrs-ch3-nostar-median-csub-1001-med2pass-cont-0021.fits
Saving residual cube to wr124-miri-mrs-ch3-nostar-median-csub-1001-med2pass-csub-0021.fits
Saving ratio cube to wr124-miri-mrs-ch3-nostar-median-csub-1001-med2pass-cdiv-0021.fits
Saving median filtered cube to wr124-miri-mrs-ch4-nostar-median-csub-1001-med2pass-cont-0011.fits
Saving residual cube to wr124-miri-mrs-ch4-nostar-median-csub-1001-med2pass-csub-0011.fits
Saving ratio cube to wr124-miri-mrs-ch4-nostar-median-csub-1001-med2pass-cdiv-0011.fits
#+end_example

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  for i in 1 2 3; do
      python ../../scripts/median_continuum.py 21 \
             wr124-miri-mrs-ch${i}-nostar-median-csub-0501.fits --two-pass --first-window-size 21 --out-label med2pass
  done

  for i in 4; do
      python ../../scripts/median_continuum.py 11 \
             wr124-miri-mrs-ch${i}-nostar-median-csub-0251.fits --percentile 20 --two-pass --out-label med2pass
  done

#+end_src

#+RESULTS:
#+begin_example
Saving median filtered cube to wr124-miri-mrs-ch1-nostar-median-csub-0501-med2pass-cont-0021.fits
Saving residual cube to wr124-miri-mrs-ch1-nostar-median-csub-0501-med2pass-csub-0021.fits
Saving ratio cube to wr124-miri-mrs-ch1-nostar-median-csub-0501-med2pass-cdiv-0021.fits
Saving median filtered cube to wr124-miri-mrs-ch2-nostar-median-csub-0501-med2pass-cont-0021.fits
Saving residual cube to wr124-miri-mrs-ch2-nostar-median-csub-0501-med2pass-csub-0021.fits
Saving ratio cube to wr124-miri-mrs-ch2-nostar-median-csub-0501-med2pass-cdiv-0021.fits
Saving median filtered cube to wr124-miri-mrs-ch3-nostar-median-csub-0501-med2pass-cont-0021.fits
Saving residual cube to wr124-miri-mrs-ch3-nostar-median-csub-0501-med2pass-csub-0021.fits
Saving ratio cube to wr124-miri-mrs-ch3-nostar-median-csub-0501-med2pass-cdiv-0021.fits
Saving median filtered cube to wr124-miri-mrs-ch4-nostar-median-csub-0251-med2pass-cont-0011.fits
Saving residual cube to wr124-miri-mrs-ch4-nostar-median-csub-0251-med2pass-csub-0011.fits
Saving ratio cube to wr124-miri-mrs-ch4-nostar-median-csub-0251-med2pass-cdiv-0011.fits
#+end_example

**** Nebular lines we have found
:PROPERTIES:
:TABLE_EXPORT_FILE: data/jwst-miri-mrs/jwst-miri-lines.tab
:TABLE_EXPORT_FORMAT: orgtbl-to-tsv
:END:

#+name: jwst-miri-lines
| Ch | Filter |     Wave | ID            |      Wave_0 |  Peak | Spatial distro   | V_hel |
|----+--------+----------+---------------+------------+-------+------------------+------|
|  1 |        |   5.1316 | H I 6-10      |   5.128657 |   200 | Diffuse          | 172. |
|  1 |        |   5.3436 | [Fe II]       |  5.3401693 |   600 | Very compact     | 193. |
|  1 |        |   5.9116 | H I 6-9       |   5.908213 |   350 | H-like           | 172. |
|  1 |        |   5.9604 | H I 7-14      |  5.9568435 |   180 | H-like           | 179. |
|  1 |        |   6.2956 | H I 7-13      |   6.291916 |   106 | V. Marginal      | 176. |
|  1 | f770w  |   6.7756 | H I 7-12      |   6.771991 |   170 | Marginal         | 160. |
|  1 | f770w  |    6.914 | H_2 S(5)       |     6.9091 |   150 | Marginal         | 213. |
|  1 | f770w  |   6.9892 | [Ar II]       |   6.985274 | 30000 | More compact     | 168. |
|  1 | f770w  |   7.4644 | H I 5-6       |   7.459858 |  3000 | H-like           | 183. |
|  1 | f770w  |   7.5068 | H I 6-8       |   7.502493 |   700 | H-like           | 172. |
|  1 | f770w  |   7.5124 | H I 7-11      |    7.50810 |   165 | H-like           | 172. |
|----+--------+----------+---------------+------------+-------+------------------+------|
|  2 | f770w  |  7.51325 | H I 7-11      |    7.50810 |   190 | Same as prev     | 206. |
|  2 | f770w  |  8.16065 | H I 8-15      |   8.154890 |    60 | Very marginal    | 212. |
|  2 | f770w  |  8.67025 | H I 8-14      |   8.664503 |    60 | Marginal diffuse | 199. |
|  2 |        |  8.76515 | H I 7-10      |   8.760064 |   250 | H-like           | 174. |
|  2 |        |  9.39825 | H I 8-13      |   9.392018 |    80 | H-like           | 199. |
|  2 |        |  9.67125 | H_2 S(3)       |     9.6649 |   175 | compact          | 197. |
|  2 |        |  10.5098 | H I 8-12      |  10.503499 |   135 | H-like           | 180. |
|  2 | f1130w |  11.3158 | H I 7-9       |  11.308695 |   450 | H-like           | 188. |
|  2 | f1130w |  11.5472 | H I 9-15      |  11.539491 |    50 | v. marginal      | 200. |
|----+--------+----------+---------------+------------+-------+------------------+------|
|  3 | f1280w |  12.1638 | H I 10-20     |  12.156833 |    20 | Diffuse          | 172. |
|  3 | f1280w |  12.2863 | H_2 S(2)       |    12.2785 |    35 | V. compact       | 190. |
|  3 | f1280w |  12.3788 | H I 6-7       |  12.371898 |  1200 | H-like           | 167. |
|  3 | f1280w |  12.3938 | H I 8-11      |  12.387168 |   110 | In wing of 6-7   | 161. |
|  3 | f1280w |  12.5938 | H I 9-14      |  12.587077 |    60 | Diffuse          | 160. |
|  3 | f1280w | 12.61875 | H I 10-19     |  12.610967 |    25 | Marginal         | 185. |
|  3 | f1280w |  12.8213 | [Ne II]       |  12.813548 | 75000 | Super strong     | 181. |
|  3 | f1280w |  13.1963 | H I 10-18     |  13.187992 |    30 | H-like           | 189. |
|  3 | f1280w |  13.9488 | H I 10-17     |  13.941764 |    35 | H-like           | 151. |
|  3 |        |  14.1913 | H I 9-13      |  14.183084 |   105 | H-like           | 174. |
|  3 |        |  14.3763 | [Cl II]       |    14.3678 |  1100 | Compact          | 177. |
|  3 |        |  14.9713 | H I 10-16     |  14.962256 |    40 | H-like           | 181. |
|  3 |        |  15.5638 | [Ne III]      |   15.55505 |    80 | V. diffuse       | 169. |
|  3 |        |  15.8263 | H I 11-20     |  15.816956 |    18 | H-like           | 177. |
|  3 |        |  16.6038 | H I 11-19     |  16.594459 |    28 | H-like           | 169. |
|  3 |        |  16.2188 | H I 8-10      |  16.209104 |   250 | H-like           | 179. |
|  3 |        |  16.4213 | H I 10-15     |  16.411724 |    40 | H-like           | 175. |
|  3 | f1800w |  16.6038 | H I 11-19     |  16.594459 |    30 | Diffuse          | 159. |
|  3 | f1800w |  16.8913 | H I 9-12      |  16.880628 |   130 | H-like           | 190. |
|  3 | f1800w |  17.0463 | H_2 S(1)       |    17.0346 |    40 | Compact          | 206. |
|  3 | f1800w |  17.8963 | [P III]       |    17.8846 |   230 | Diffuse          | 196. |
|  3 | f1800w |  17.9463 | [Fe II]       |  17.936026 |   350 | V. Compact       | 172. |
|----+--------+----------+---------------+------------+-------+------------------+------|
|  4 | f1800w |  17.9463 | [Fe II]       |  17.936026 |   350 | V. Compact       | 172. |
|  4 | f1800w |   18.627 | H I 10-14     |  18.615150 |    30 | V. marginal      | 191. |
|  4 | f1800w |   18.723 | [S III]       |   18.71303 | 35000 |                  | 160. |
|  4 | f1800w |   19.071 | H I 7-8       |  19.061898 |   500 | H-like           | 143. |
|  4 |        |   21.873 | UIL           |     21.861 |    90 | V. diffuse       | 165. |
|  4 |        |   22.347 | He I 9g-11f T | 22.3331956 |   140 | Diffuse          | 185. |
|  4 |        |   22.941 | [Fe III]      |    22.9250 |  1000 | Compact          | 209. |
|  4 |        |   24.531 | UIL           |     24.517 |    60 | H-like           | 171. |
|  4 |        |   26.007 | [Fe II]       |  25.988390 |   650 | V. compact       | 215. |
|  4 |        |   27.273 | UIL           |     27.258 |   160 |                  | 165. |
#+TBLFM: $8=$5 > 0 ? $c ($3 - $5) / $5 $km : $3 (1 - (180 $km / $c)) 10000 ;f0
- Note that the [Ne III] 10.863, which we detected in the Spitzer IRS spectra turns out to be entirely stellar, with no nebular component at all
  - [-] But we do detect a nebular component for [Ne III] 15.5638 (as well as a stellar wind one)
  - This is probably due to the difference in A values, which is much lower for [Ne III] 10.863
- Also note that [Fe II] 17.936 is seen in ch4 as well as ch3
  - And we see more knots in ch4 because the FOV is larger
- Location of some artefact that could be mistaken for lines:
  - 18.663
  - 12.09, 12.10
  - 14.8173 (previously He I but definitely artefact)
- Save the table to a file with ~C-c t e~


**** Test reading the table
  #+begin_src python :results output :dir data/jwst-miri-mrs
    from astropy.table import Table
    tab = Table.read("jwst-miri-lines.tab", format="ascii.tab")
    print(tab)
  #+end_src

  #+RESULTS:
  #+begin_example
   Ch Filter   Wave        ID        Wave_0    Peak Spatial distro V_hel
  --- ------ ------- ------------- ---------- ----- -------------- -----
    1     --  5.1316      H I 6-10   5.128657   200        Diffuse 172.0
    1     --  5.3436       [Fe II]  5.3401693   600   Very compact 193.0
    1     --  5.9116       H I 6-9   5.908213   350         H-like 172.0
    1     --  5.9604      H I 7-14  5.9568435   180         H-like 179.0
    1     --  6.2956      H I 7-13   6.291916   106    V. Marginal 176.0
    1  f770w  6.7756      H I 7-12   6.771991   170       Marginal 160.0
    1  f770w   6.914      H_2 S(5)     6.9091   150       Marginal 213.0
    1  f770w  6.9892       [Ar II]   6.985274 30000   More compact 168.0
    1  f770w  7.4644       H I 5-6   7.459858  3000         H-like 183.0
    1  f770w  7.5068       H I 6-8   7.502493   700         H-like 172.0
  ...    ...     ...           ...        ...   ...            ...   ...
    3 f1800w 17.9463       [Fe II]  17.936026   350     V. Compact 172.0
    4 f1800w 17.9463       [Fe II]  17.936026   350     V. Compact 172.0
    4 f1800w  18.627     H I 10-14   18.61515    30    V. marginal 191.0
    4 f1800w  18.723       [S III]   18.71303 35000             -- 160.0
    4 f1800w  19.071       H I 7-8  19.061898   500         H-like 143.0
    4     --  21.873           UIL     21.861    90     V. diffuse 165.0
    4     --  22.347 He I 9g-11f T 22.3331956   140        Diffuse 185.0
    4     --  22.941      [Fe III]     22.925  1000        Compact 209.0
    4     --  24.531           UIL     24.517    60         H-like 171.0
    4     --  26.007       [Fe II]   25.98839   650     V. compact 215.0
    4     --  27.273           UIL     27.258   160             -- 165.0
  Length = 53 rows
  #+end_example

*** Make maps of the nebular lines
- [2023-11-16 Thu] Return to this now that we have done the star subtraction
- We will use cubes such as
  : wr124-miri-mrs-ch1-nostar-median-csub-1001-median-csub-0021.fits
- Strategy is to just find the moments in a narrow window
  - Looks like 7 pixels would be fine
  - Pixel width is about 50 km/s in blue, decreasing across each band
    - Except 100 km/s in case of Ch4
  - Maybe it would be better to use a fixed velocity range
    - For instance +50 to +350 km/s
    - H I 7-10 wav0=8.760064 so 8.760064 (1 + [50 .. 350]/3e5) = [8.76152 .. 8.77028]
    - Which is 963 .. 970
    - This is fine for that line, but we may want to increase range for ch4




Channel 1
#+begin_src sh :dir data/jwst-miri-mrs :results silent
  python ../../scripts/make-line-maps.py wr124-miri-mrs-ch1_s3d-median-csub-0021.fits --out-path LineMaps0021
#+end_src
Channel 2
#+begin_src sh :dir data/jwst-miri-mrs :results silent
  python ../../scripts/make-line-maps.py wr124-miri-mrs-ch2_s3d-median-csub-0021.fits --out-path LineMaps0021
#+end_src
Channel 3
#+begin_src sh :dir data/jwst-miri-mrs :results silent
  python ../../scripts/make-line-maps.py wr124-miri-mrs-ch3_s3d-median-csub-0021.fits --out-path LineMaps0021
#+end_src
Channel 4
#+begin_src sh :dir data/jwst-miri-mrs :results silent
  python ../../scripts/make-line-maps.py wr124-miri-mrs-ch4_s3d-median-csub-0011.fits --out-path LineMaps0021
#+end_src


#+RESULTS:


#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/make-line-maps.py --help
#+end_src

#+RESULTS:
#+begin_example
Usage: make-line-maps.py [OPTIONS] CUBE_PATH

  Construct a brightness map for each line in table

  Each line is integrated over VELOCITY_RANGE_KMS

Arguments:
  CUBE_PATH  [required]

Options:
  --hdu-key TEXT                  [default: SCI]
  --line-table-path PATH          [default: jwst-miri-lines.tab]
  --velocity-range-kms <FLOAT FLOAT>...
                                  [default: 0.0, 400.0]
  --out-path PATH                 [default: /Users/will/Dropbox/globule-
                                  seminario/m1-67/data/jwst-miri-mrs/LineMaps]

  --verbose / --no-verbose        [default: True]
  --install-completion            Install completion for the current shell.
  --show-completion               Show completion for the current shell, to
                                  copy it or customize the installation.

  --help                          Show this message and exit.
#+end_example

*** Initial impressions of the line maps
:PROPERTIES:
:ID:       37A312EC-577B-46EF-A08E-4BCDA595A848
:END:
- [S III] line shows line width increasing at lower intensity
  - This could be real, or it could be an artefact of the median filtering
- The supposed He I line at 14.804 micron has some weird artefacts parallel to detector minor axis, but otherwise looks like the H I lines more or less - /but still no good/
- The He I 9g-11f triplet line at 22.333 micron is better
  - [ ] Why is this the only He I line that is clearly separated from H I lines?
    - I have searched and searched for additional He I lines, but to no avail
  - It has interesting differences from the H I 7-8 line at 19.06 micron
    - In Knot A we have 22.333 / 19.06 = (384+/-71)/(696+/-59) = 0.55 +/- 0.03
    - In Knot B we have 22.333 / 19.06 = (247+/-60)/(622+/-86) = 0.40 +/- 0.03
  - So the closer (projected) knot has a larger He I/H I ratio
  - [ ] /We can calibrate this using pyneb/
    - Although we need to take into account potential He I contributions to H I 19.061898
- [Ne III]
  - The 10.863 line is not seen in nebula but is seen in stellar wind
  - The 15.555 line is seen in nebula and has a spectacularly different distribution to any other line
  - *It seems to come only from the bow shock shells and not from the knots at all*
- [Fe II] and [Fe III]
  - This shows the opposite trend to He I / H I
  - Knot A has a lower [Fe III]/[Fe II] ratio than Knot B
- Comparison of ionization state between knots
  - For the H I lines we have *bkg/A = 0.08* and bkg-subtracted *B/A = 1, C/A = 0.35*
  - This repeats some material from above, but with additional lines
  - We cannot use [Ne III]/[Ne II] since [Ne III] does not come from the knots
  - But we could look at ratios with nearby H lines
  - [Ar II] 6.985274 vs H I 5-6 7.459858
    - In small FOV of ch1 so only covers knot A unfortunately
  - [Ne II] 12.813548 vs H I 6-7 12.371898
    - Ratio is very similar between Knots A and B
    - Not surprising if Ne^+ is the dominant ion stage
  - [S III] 18.71303 vs H I 7-8 19.061898
    - B/A = 1.0, C/A = 0.39 so similar to H I
    - Again, presumably because S^++ is dominant ion stage
  - [P III] has the same behavior with B/A = 1
    - But Knot C is much brighter in this line: C/A = 0.96
  - [Fe III] 22.9250
    - bkg, A, B, C = 600, 1985, 2303, 2918
    - B/A = 1.23, C/A = 1.67
    - Very different, and also displaced outward within knots, especially B
  - [Fe II] 17.9360
    - bkg, A, B, C = 10, 406, 229, 202
    - B/A = 0.55, C/A = 0.48
    - Also different, and displaced inward in Knot B
    - Note: inward and outward are with respect to knot center
  - He I 22.3332
    - bkg, A, B, C = 10, 347, 271, 55
    - B/A = 0.77, C/A = 0.133
  - We can also use Ha from the HST images
    - Need separate bkg for A, since PSF wings of star are significant
    - bkgA, bkgBC, A, B, C = 0.8, 0.2, 2.5, 2.0, 0.98
    -  B/A = 1.05, C/A = 0.46

*** Make maps of the medium width features
- Options for how to proceed with this
  1. We could use PAHfit
     - Pro :: industry standard
     - Pro :: would also fit some lines
     - Pro :: maybe we could customize it to fit all the lines
     - Con :: something new to learn
     - Con :: unclear if fast enough to employ pixel by pixel on the cubes
     - Con :: would be hard to combine with the stellar continuum removal (see below)
  2. Or we could try median filtering them into submission
  3. Or we could just measure the excess in a certain wav range
     - Pro :: this is simpler
     - Pro :: we only need a certain number of PAH bands to characterise the filter contributions: 7.7, 8.6, 11.2, 12.7
     - Con :: we need to think carefully about the continuum level
  4. Or we could fit some template spectra
     - Pro :: this should be efficient
     - Con :: where do we get the templates from?
     -  :: 

**** What is the filter combo to use for PAH features?
- Should be
  : wr124-miri-mrs-ch1-nostar-median-csub-0501-med2pass-cont-0021.fits
  : wr124-miri-mrs-ch2-nostar-median-csub-0501-med2pass-cont-0021.fits
  : wr124-miri-mrs-ch3-nostar-median-csub-0501-med2pass-cont-0021.fits
  : wr124-miri-mrs-ch4-nostar-median-csub-0251-med2pass-cont-0011.fits

This still has some pass through of H lines form wind, but it will do for now
**** Table of AIBs
:PROPERTIES:
:TABLE_EXPORT_FILE: data/jwst-miri-mrs/jwst-miri-bands.tab
:TABLE_EXPORT_FORMAT: orgtbl-to-tsv
:END:

#+name: jwst-miri-bands
| Ch | Band     | wavmin | wavmax |
|----+----------+--------+--------|
|  1 | AIB 6.2  |    6.1 |    6.3 |
|  1 | AIB 7.7  |    7.5 |   7.65 |
|  2 | AIB 7.7  |    7.8 |   8.15 |
|  2 | AIB 8.6  |    8.5 |    8.8 |
|  2 | AIB 11.2 |   11.1 |   11.5 |
|  3 | AIB 12.7 |   12.6 |   13.0 |
|  3 | AIB 13.5 |   13.3 |   13.8 |
|  3 | AIB 16.5 |   16.3 |   16.8 |
|  3 | AIB 17.4 |   17.1 |   17.7 |
|  4 | AIB 18.9 |   18.7 |   19.0 |
|  4 | AIB 24.6 |   24.4 |   24.8 |
- Save table with ~C-c t e~
- With the exception of 24.6, all these are bands included in PAHfit
- The majority peak in the knots, with the following exceptions
  - 8.6 seems more diffuse
  - 17.4 is also diffuse and better s/n
  - 24.6 is a bit of a mess
**** Run the script to extract the band maps
- Simplified version of the spectral line extraction

Channel 1
#+begin_src sh :dir data/jwst-miri-mrs :results silent
  python ../../scripts/make-band-maps.py wr124-miri-mrs-ch1-nostar-median-csub-0501-med2pass-cont-0021.fits
#+end_src
Channel 2
#+begin_src sh :dir data/jwst-miri-mrs :results silent
  python ../../scripts/make-band-maps.py wr124-miri-mrs-ch2-nostar-median-csub-0501-med2pass-cont-0021.fits
#+end_src
Channel 3
#+begin_src sh :dir data/jwst-miri-mrs :results silent
  python ../../scripts/make-band-maps.py wr124-miri-mrs-ch3-nostar-median-csub-0501-med2pass-cont-0021.fits
#+end_src
Channel 4
#+begin_src sh :dir data/jwst-miri-mrs :results silent
  python ../../scripts/make-band-maps.py wr124-miri-mrs-ch4-nostar-median-csub-0251-med2pass-cont-0011.fits
#+end_src


**** Initial comments on the band maps
[2023-11-21 Tue]
+ The AIB 6.2 band in ch01 clearly shows that knot A divides into 3 components
  + The closest-in component coincides exactly with the "Fe II tip" region that I had previously identified
  + The sigma is about 0.04 micron, implying a FWHM of 0.1 micron, which is less than the 0.19 micron that PAHfit has
+ AIB 7.7 and 8.6 are much noisier but show essentially the same structure
  + 7.7 is not helped by straddling ch01 and ch02
+ AIB 11.2 is much higher s/n and also shows the same structure, although the resolution is degraded with respect to 6.2
  + We can also see part of knot B
+ AIB 12.7 is also good s/n and is brighter in B than A
+ AIB 13.5 is very diffuse
  + Possibly, it is nothing but noise and artifacts
+ AIB 16.5 shows the knots nicely
+ AIB 17.4 is diffuse and a bit swamped by artifacts,
  + although it is definitely a feature
  + even though its spatial distribution is hard to discern
+ AIB 18.9 shows the three knots A, B, C
  + A and B are similar brightness
  + which agrees with 11.2 (from the filter imaging)
  + but differs from 12.7, which has B brighter
+ AIB 24.6 micron is just a bunch of noise

*** Repeat but for the continuum bands
- 7-9 micron seems to be the broad pedestal of the PAH band
- Very flat 9-14
- Then starts rising 15-30
  - In Knot A it is always rising
  - In Knot B and C it peaks at 26 (B) or 25 (C)

*** Make synthetic maps of the MIRI filters
- Use the median filtered cubes to separate out different components
  - Nebular lines
  - UIB features
  - Featureless continuum
  - Stellar wind lines?
- Make maps for each MRI filter of the contributions of each
*** Dealing with the stellar contribution
- The median filtered (N=21) "cont" component should be a good representation of the stellar spectrum (continuum plus broad lines).
- We could then just scale and subtract this component for all the other pixels and/or apertures
- This is only necessary for the UIB and dust continuum, since the median filtering already solves the problem for the nebular lines
- 
**** Big plan for the PSF removal
- Note that we cannot use WebbPSF since they do not support spectral cubes
  - From [[https://www.stsci.edu/jwst/science-planning/proposal-planning-toolbox/psf-simulation-tool][WebbPSF documentation]] (checked [2023-11-14 Tue 12:38])
    : Limitations: The spectroscopy modes of NIRSpec and MIRI are not yet supported.
  - On the other hand, it also says
    : What this software does NOT do: ... Model spectrally dispersed PSFs produced by any of the spectrograph gratings. It does, however, let you produce monochromatic PSFs in these modes, suitable for stitching together into spectra using some other software.
  - So it looks like we could generate PSFs at a few different wavelengths and then interpolate from those
  - This might even be better ....
    - There is even a ~calc_datacube()~  function for this (see [[https://webbpsf.readthedocs.io/en/stable/usage.html#calculating-data-cubes][Calculating Data Cubes]] in docs)
  - The only tedious bit with this approach would be interpolating onto the WCS of the pipeline-reduced cubes
    - Since the files I have do not have the original detector coordinates
- The big advantage we have is the broad stellar wind lines
  - These unambiguously come from a point source
  - And they can be isolated by the median filter chain:
    - cont-021 + csub-081 (or 401 or whatever)
  - This gives a series of PSF maps at discrete wavelengths of the lines
    - Usually 3 or 4 of the strongest per channel
  - We can wave-interpolate a PSF cube from these
    - Better results would come from parameterizing the PSF and interpolating the parameters, but that sounds like too much work
- Then we need to get a pure stellar spectrum
  - Continuum plus broad lines
- We can use the "Star" box in the ~cont-021~ cube for this, since it should have pretty much zero contribution from the nebula
  - The nebular lines have been all filtered out
  - There is no PAH emission that overlaps the star
  - There may be some dust emission at long wavelengths, but remember that this is going to be multiplied the PSF and subtracted, so that is not a worry
  - The PSF petals that overlap with the knots are 300 times fainter than the PSF peak
  
**** DONE Construct the PSF cubes
CLOSED: [2023-11-15 Wed 19:11]

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/find-cube-psf.py wr124-miri-mrs-ch1 --radius-arcsec 0.2 --polynomial-degree 1 > /dev/null
#+end_src

#+RESULTS:

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/find-cube-psf.py wr124-miri-mrs-ch2 --radius-arcsec 0.3 --polynomial-degree 1 > /dev/null
#+end_src

#+RESULTS:

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/find-cube-psf.py wr124-miri-mrs-ch3 --radius-arcsec 0.6 --max-radius-arcsec 3.0 --polynomial-degree 1 > /dev/null
#+end_src

#+RESULTS:

Channel 4 is different since filters are narrower in pixels.  Also, the long wavelength end is very noisy, so we do not want to use it
#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/find-cube-psf.py wr124-miri-mrs-ch4 --mid-pass-suffix median-cont-0011-median-csub-0075 --max-wavelength-micron 25 --radius-arcsec 1.0 --max-radius-arcsec 4.0 --polynomial-degree 1 > /dev/null
#+end_src

#+RESULTS:
**** TODO Use the PSF cubes to remove the stellar spectrum
- We should get the stellar spectrum from the ~median-cont-0021~ since that should have the nebular lines (that overlap with the star) removed
- But we should subtract it from the original cube, which should give us a residual that is just
  1. Dust continuum, d\lambda/\lambda = 1
  2. PAH features, d\lambda/\lambda = 0.02 - 0.1
  3. Nebular lines, d\lambda/\lambda = 0.0003 - 0.001 (mainly instrumental profile)
- Then we can try the top-down median filtering to extract each of these in turn

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/remove-star-spectrum.py wr124-miri-mrs-ch1 --noneb-cube-suffix median-cont-0021 --radius-arcsec 0.2
#+end_src

#+RESULTS:
: Saving star contribution to cube to wr124-miri-mrs-ch1-star.fits
: Saving star-subtracted nebula cube to wr124-miri-mrs-ch1-nostar.fits

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/remove-star-spectrum.py wr124-miri-mrs-ch2 --noneb-cube-suffix median-cont-0021 --radius-arcsec 0.3
#+end_src

#+RESULTS:
: Saving star contribution to cube to wr124-miri-mrs-ch2-star.fits
: Saving star-subtracted nebula cube to wr124-miri-mrs-ch2-nostar.fits

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/remove-star-spectrum.py wr124-miri-mrs-ch3 --noneb-cube-suffix median-cont-0021 --radius-arcsec 0.6
#+end_src

#+RESULTS:
: Saving star contribution to cube to wr124-miri-mrs-ch3-star.fits
: Saving star-subtracted nebula cube to wr124-miri-mrs-ch3-nostar.fits

#+begin_src sh :dir data/jwst-miri-mrs :results output verbatim
  python ../../scripts/remove-star-spectrum.py wr124-miri-mrs-ch4 --noneb-cube-suffix median-cont-0011 --radius-arcsec 1.0
#+end_src

#+RESULTS:
: Saving star contribution to cube to wr124-miri-mrs-ch4-star.fits
: Saving star-subtracted nebula cube to wr124-miri-mrs-ch4-nostar.fits
