Analysis of the reprojected maps and ratios thereof for m1-67

* Summary of what we have done and what needs to be done

** Focus for Roberto's thesis
- We want to get a better estimate of the knot radii, which is difficult to obtain from the HST H alpha images
- Also, if there is some way from the JWST images to isolate the interaction shells based on the line ratios, rather than simply morphology then that would be great

** What we have done as of now [2024-05-26 Sun]
- Summary of how all the ratios vary between different spatial zones in [[id:333074B1-5DDA-4B69-8160-AA04E6D2C78C][Qualitative analysis of the different ratios]]
- Analysis of relative contributions (lines, UIB, continuum) to the different filters
  - But only possible for the MIRI filters
  - Spitzer IRS for the whole nebula
    - See the various subsections of [[id:8ABE921C-EF8A-443A-8C7D-EEBF4AA6A923][MIRI Imaging]] in [[file:m1-67-globules.org]]
    - [[id:BAFF43C0-68C4-47A1-9407-D85507D04941][Summary table from Spitzer spectra]]
    - [[id:270E26FA-B168-4712-9A28-8C028C2AE4DF][Predictions for behavior of each filter]]
    - [[id:7BA17133-6976-4A86-BF36-D8F8CAAD3587][Predictions for what factors influence the colors]]
    - [[id:D33313A5-52A2-412F-B2AE-BE76DB57CB6E][Detailed inventory of each filter]] 
  - JWST for the little globules near the star
    - The only thing I found was [[id:9F49EDEC-433C-4193-904B-785AF4C0E86F][Conclusions based on the contribution fractions]]
    - We could do more with this, such as getting a better handle on what the color variations are due to 
  - [ ] I need to try and reconcile the two sets of results. They need not give exactly the same since they are studying different regions. In fact the variation between them can be instructive

** TODO Things to do next
:LOGBOOK:
- Note taken on [2024-06-04 Tue 13:24] \\
  I am going to work on the star mask next, since that is a pre-requisite for doing good color-color plots
- Note taken on [2024-06-04 Tue 11:10] \\
  I have now done the smoothing. This did not make an enormous difference, but it did successfully eliminate some of the artefacts, such as the ghost tadpoles in some of the MIRI ratios
:END:
- [X] Smoothing of band maps to a common PSF before taking ratios
  - This is something I had asked Roberto to do, but I do not think he ever did it
  - We only need to do this in groups, so we would still maintain the resolution of the longest wavelength filter in each group: f220w, f444w, f1800w
  - This is what we should do first before any other analysis
- [ ] Write python script to make images of the band maps and the ratios, including the rgb color combination maps that I have been using
- [ ] Do correlation color-color plots for all the band ratios
  - Maybe even separate out the shell and core regions for each knot, as determined from the H alpha HST analysis, and compare with the diffuse emission
  - And also how it varies with distance from the star and between the two sides along the major axis
- [ ] See if there are linear combinations of bands that we can use to remove the ionized emission to some extent and leave the pure knots
  - And the same for the stars
    - For instance, the f210m/f150w ratio is almost featureless at 1.6-1.8 in the nebula (ionized gas and neutral globules), but goes down to 0.8-1.0 in the stars (stars are bluer)
    - This means that if we take ~f150w - f210m/1.7~ we should cancel out the nebula and see just the stars
- [ ] Based on the previous, we could make the best possible star mask for each band. If we had a good pure star brightness map at 2.1 microns, then we can smooth it to the resolution of each band and make a bespoke mask, according to star/nebula at that wavelength and that resolution
- Use the different bands to get better positions for the center of each knot
  - Presumably the f335w band would be best
- Plot radial profiles of the bands and ratios for each knot
- Finish the analysis of the MIRI spectra, which seems to have been left 95% done

* Using ratios to diagnose different spatial zones
- The principal zones that we can divide the nebula into are
  1. The stars
  2. The neutral globules
  3. The ionized gas
     - particularly the interaction shells
     - but also the photoevaporation flows from the knots
     - and also the other shells in the outside of the nebula that have different morphologies
  4. The diffuse component that emits at 18 microns
** Qualitative analysis of the different ratios
:PROPERTIES:
:ID:       333074B1-5DDA-4B69-8160-AA04E6D2C78C
:END:
*** Short band NIRCAM
- Start with f090w brightness (not strictly a ratio, I know ...)
  - This mainly shows the ionized gas, with the following components
    - The ionization fronts on the knot heads (typical peak of 2 to 5 above background)
    - The interaction shells (typical peak of 1 above the background)
    - The "collars" in between the head and the tail of the knots, as seen in simulations (typical peak of 1 to 1.5)
      - The combination of the collars and the interaction shells can give the illusion of a closed spherical shell
    - [Very weakly] the tails of the knots (peaks of 0.5 or less)
    - [Even weaker] shells and diffuse emission from the outer parts of the nebula (peaks of 0.2 to 1.5).
  - Also shows the stars. Even faint stars have peaks above 10
- f150w/f090w
  - Value about 1.0 in the ionized gas
  - Falls to about 0.7 to 0.8 in diffuse/faint, but noisy
  - Goes up to 1.3 to 1.4 in the neutral globules
    - Has a fan like structure that is not seen in the other ratios, as if it were a shadow cast by the knot heads' ionization front.
    - Decreases to about 1.2 in the knot tails, but extends to larger distances down the tail than the other neutral tracers
  - Goes up to higher than 2 in the stars, so stars are REDDER than nebula
- f210m/f150w
  - Shows very little structure, with typical value of 1.6 to 1.8 in most of the nebula with ionized emission
  - Falls to about 1.0 to 1.1 in the faint zones dominated by diffuse dust
  - Falls to values of 0.8 to 1.0 at the positions of stars, so stars are BLUER than nebula
  - Almost no structure in the globules. Looking at the map you could not say where the ionization front might be
*** Long band NIRCAM
- f335m brightness
  - We see the ionized gas weakly, but the knots much more strongly
- f335m/f220w
  - Value about 1.0 in the ionized gas
  - Falls to about 0.7 to 0.8 in the diffuse/faint zones
  - Goes up to 2 to 4 in the neutral globule heads
    - Falling by a factor of 2 as you go down the tail
    - The peak in the ratio occurs just behind the peak in the f335m brightness (as in, more towards the tail)
    - [ ] We get strange local minima in the ratio at the knot heads, but I wonder if this might just be due to the mismatch in the angular resolution. We see something similar when we divide the f090w by the HST f656n images.
      - I need a version where I smooth to the lowest common denominator before taking the ratio
  - Stars have a much lower value of 0.2 to 0.3
- f444w/f335m
  - Value about 2.0 in the ionized gas
  - Falls to about 1.2 to 1.5 in the diffuse/faint zones
  - Drops to about 1.0 in the knot heads, rising back up to about 1.5 as you go down the tail
  - Value is about 0.8 in the stars
- f470n/f444w
  - Previously discussed in [[id:E6DB5862-941F-494F-883C-7A72C9894BDC][Strange behavior of the f470n filter]]
  - Value of 0.6 to 0.65 in dense ionized gas
  - Peaks of 0.8 to 0.9 in the globule heads
  - Higher values in diffuse faint regions, but that might be zero point issues
  - Also high values of around 1.0 in filamentary shock region around PA 70 and R = 10 to 12 arcsec. This is just outside a region that shows atypical ratios between other MIRI bands
*** Interband ratio
- f777w/f444w
  - Value of about 3.5 to 4.0 in the ionized gas, at least in the interaction shells
    - More like 5 close to the ionization front on the knot's head
    - Also 4.5 to 5 in the diffuse emission in the general nebula
  - Goes up to 10 in the neutral globules
    - Still stays as high as 8, even after going a way down the tail
  - Low value of 0.2 to 1.0 in the stars
  - This ratio is really interesting. It traces very well the outward-facing shocked shells in the outer parts of the nebula. And some in the inner part as well
    - Strangely, they have a low value of this ratio: 3.3 to 4.0, as opposed to the 4.5 to 5.0 in the diffuse ionized emission
    - [ ] I ought to be able to work out what is causing this by looking at the mid-infrared spectra - Spitzer and JWST
*** MIRI band
- General notes on these ratios
  - f1130w/f777w is to a large extent correlated with f1800w/f1280w, at least on the scale of the entire nebula, 
  - f1280w/f1130w seems anti-correlated with these two. Also,  f1280w/f1130w does not have the same lop-sidedeness
  - Note that it is f1130w and f1800w that show the least lopsidedness in their emission. This seems contradictory, need to check later
**** f1130w/f777w
- In the ionized gas shows the shell structure moderately well (in negative), but it is the hexagon-like structure formed by the interactions between the flanks of knots that show up better than the interaction shells in front of the head
  - with values of 0.5 to 1.0 in all these shells
  - As compared with 1.5 in the gaps
- And sometimes as high as 3 to 3.5 in the diffuse/faint regions on the NE axis and northern tropics at larger radii
- Also value of around 1.0 in the  outward-facing shock filaments in the outer parts of the nebula
- Reaches even lower values of 0.5 in outer diffuse ionization front
- Shows strange tadpole behaviour in the globules, which may be in part due to the mismatch in resolution, but on average the ratio is about 1 to 1.6 in the globules
- Stars have a range of values from 0.4 (bright stars) to 1.0 (faint stars)
- Clear gradient along the major axis off the nebula (NE to SW) with values of 0.5 to 1.0 in the NE and 1.0 to 1.5 in the SW
  - Average value of 2 on the faint side (NE) versus 1 on the bright side (SW)
**** f1280w/f1130w
- In the ionized gas, shows the shell structure well, more focused towards the frontal interaction shells than is the case for f1130w/f777w
  - with values of 3.0 to 4.0 in the interaction shells
  - As compared with 2.5 to 3.5 in the gap between i-front and shell (there is always a consistent difference of 0.5 between the two ratios)
  - And 2.5 to 3 in the diffuse ionized gas
- In the diffuse/faint regions it falls to 1.5 to 2.0
- Highest values of 5 to 6 are seen in ionized filaments that are not associated with knots
  - Innermost one at (pa-sep) 058-067
  - Another one at 120-300 approx, with a chain of filaments/knots, which look like a jet on the HST H alpha image
  - Also, in the outskirts of the nebula, which I had thought of as ionization fronts but are maybe wind-blown shells
- In the globules, the ratio is about 1.2 to 1.5 in the globule head, gradually climbing in the tails back up to 2.5 to 3.0
**** f1800w/f1280w
- In the ionized gas shows the shell structure very well (in negative), with values of 1.5 to 2.0 in the interaction shells
  - As compared with 2.5 to 3.0 in the gap between i-front and shell
  - And 3 to 3.5 in the diffuse ionized gas
  - [ ] Note that the MIRI ratio shell is on the inner (star-side) edge of the emission shell - we should discuss this somewhere else
- Reaches even lower values of 1.0 to 1.5 in the outwards facing shells in the outer parts of the nebula
- Globules have a value of about 2 and are not very prominent at all.
  - Only the heads are seen at all - the tails are completely invisible in this ratio, suggesting that it is the ionized emission that we are picking up
* Matching resolutions before taking ratios
** JWST NIRCam short
#+begin_src sh :dir data/reproject :results verbatim
  python ../../scripts/find-ratio.py \
         wr124-jwst-nircam-2022-f150w-radec.fits \
         wr124-jwst-nircam-2022-f090w-radec.fits \
         ratio-f150w-f090w-match-f210m.fits \
         --bg-a 0.22 --bg-b 0.2 \
         --match-psf --debug --match-psf-to jwst-f210m
#+end_src

#+RESULTS:
: Pixel scale: 0.0310 arcseconds
: Wavelengths: Filter A = 1.50 Filter B = 0.90
: PSF FWHM (pixels): Filter A = 1.6 Filter B = 1.0 Match to = 2.2

#+begin_src sh :dir data/reproject :results verbatim
  python ../../scripts/find-ratio.py \
         wr124-jwst-nircam-2022-f210m-radec.fits \
         wr124-jwst-nircam-2022-f150w-radec.fits \
         ratio-f210m-f150w-match-f210m.fits \
         --bg-a 0.1 --bg-b 0.22 \
         --match-psf --debug 
#+end_src

#+RESULTS:
: Pixel scale: 0.0310 arcseconds
: Wavelengths: Filter A = 2.10 Filter B = 1.50
: PSF FWHM (pixels): Filter A = 2.2 Filter B = 1.6 Match to = 2.2
** JWST NIRCam long
#+begin_src sh :dir data/reproject :results verbatim
  python ../../scripts/find-ratio.py \
         wr124-jwst-nircam-2022-f335m-radec.fits \
         wr124-jwst-nircam-2022-f210m-radec.fits \
         ratio-f335m-f210m-match-f470n.fits \
         --bg-a 0.15 --bg-b 0.1\
         --match-psf --debug --match-psf-to jwst-f470n
#+end_src

#+RESULTS:
: Pixel scale: 0.0310 arcseconds
: Wavelengths: Filter A = 3.35 Filter B = 2.10
: PSF FWHM (pixels): Filter A = 3.6 Filter B = 2.2 Match to = 5.0

This removes some of the artefacts that we were seeing at the globule heads before

Now, check with one that just does the bare minimum of smoothing for this ratio alone
#+begin_src sh :dir data/reproject :results verbatim
  python ../../scripts/find-ratio.py \
         wr124-jwst-nircam-2022-f335m-radec.fits \
         wr124-jwst-nircam-2022-f210m-radec.fits \
         ratio-f335m-f210m-match-f335m.fits \
         --bg-a 0.15 --bg-b 0.1\
         --match-psf --debug --match-psf-to jwst-f335m
#+end_src

#+RESULTS:
: Pixel scale: 0.0310 arcseconds
: Wavelengths: Filter A = 3.35 Filter B = 2.10
: PSF FWHM (pixels): Filter A = 3.6 Filter B = 2.2 Match to = 3.6

#+begin_src sh :dir data/reproject :results verbatim
  python ../../scripts/find-ratio.py \
         wr124-jwst-nircam-2022-f444w-radec.fits \
         wr124-jwst-nircam-2022-f335m-radec.fits \
         ratio-f444w-f335m-match-f470n.fits \
         --bg-a 0.2 --bg-b 0.18 \
         --match-psf --debug --match-psf-to jwst-f470n
#+end_src

#+RESULTS:
: Pixel scale: 0.0310 arcseconds
: Wavelengths: Filter A = 4.44 Filter B = 3.35
: PSF FWHM (pixels): Filter A = 4.7 Filter B = 3.6 Match to = 5.0

#+begin_src sh :dir data/reproject :results verbatim
  python ../../scripts/find-ratio.py \
         wr124-jwst-nircam-2022-f470n-radec.fits \
         wr124-jwst-nircam-2022-f444w-radec.fits \
         ratio-f470n-f444w-match-f470n.fits \
         --bg-a 0.2 --bg-b 0.2 \
         --match-psf --debug --match-psf-to jwst-f470n
#+end_src

#+RESULTS:
: Pixel scale: 0.0310 arcseconds
: Wavelengths: Filter A = 4.70 Filter B = 4.44
: PSF FWHM (pixels): Filter A = 5.0 Filter B = 4.7 Match to = 5.0
** JWST MIRI
First do MIRI/NIRCAM matched to f1800w and to f770w. This loses a lot of the definition of the shocked shells, which means that some of that was an artefact of the mismatched resolutions. But they are still apparent, especially in the f770w version. The f1800w version is much more diffuse, but that is only necessary for comparing with the longer wave ratios
#+begin_src sh :dir data/reproject :results verbatim
  python ../../scripts/find-ratio.py \
         wr124-jwst-miri-2022-f770w-radec.fits \
         wr124-jwst-nircam-2022-f444w-radec.fits \
         ratio-f770w-f444w-match-f1800w.fits \
         --bg-a 7.0 --bg-b 0.2 \
         --match-psf --debug --match-psf-to jwst-f1800w
#+end_src

#+RESULTS:
: Pixel scale: 0.0310 arcseconds
: Wavelengths: Filter A = 7.70 Filter B = 4.44
: PSF FWHM (pixels): Filter A = 8.2 Filter B = 4.7 Match to = 19.2

#+begin_src sh :dir data/reproject :results verbatim
  python ../../scripts/find-ratio.py \
         wr124-jwst-miri-2022-f770w-radec.fits \
         wr124-jwst-nircam-2022-f444w-radec.fits \
         ratio-f770w-f444w-match-f770w.fits \
         --bg-a 7.0 --bg-b 0.2 \
         --match-psf --debug --match-psf-to jwst-f770w
#+end_src

#+RESULTS:
: Pixel scale: 0.0310 arcseconds
: Wavelengths: Filter A = 7.70 Filter B = 4.44
: PSF FWHM (pixels): Filter A = 8.2 Filter B = 4.7 Match to = 8.2

Then interband of MIRI
#+begin_src sh :dir data/reproject :results verbatim
  python ../../scripts/find-ratio.py \
         wr124-jwst-miri-2022-f1130w-radec.fits \
         wr124-jwst-miri-2022-f770w-radec.fits \
         ratio-f1130w-f770w-match-f1800w.fits \
         --bg-a 23.0 --bg-b 7.0 \
         --match-psf --debug --match-psf-to jwst-f1800w
#+end_src

#+RESULTS:
: Pixel scale: 0.0310 arcseconds
: Wavelengths: Filter A = 11.30 Filter B = 7.70
: PSF FWHM (pixels): Filter A = 12.0 Filter B = 8.2 Match to = 19.2

#+begin_src sh :dir data/reproject :results verbatim
  python ../../scripts/find-ratio.py \
         wr124-jwst-miri-2022-f1280w-radec.fits \
         wr124-jwst-miri-2022-f1130w-radec.fits \
         ratio-f1280w-f1130w-match-f1800w.fits \
         --bg-a 26.0 --bg-b 23.0 \
         --match-psf --debug --match-psf-to jwst-f1800w
#+end_src

#+RESULTS:
: Pixel scale: 0.0310 arcseconds
: Wavelengths: Filter A = 12.80 Filter B = 11.30
: PSF FWHM (pixels): Filter A = 13.6 Filter B = 12.0 Match to = 19.2

#+begin_src sh :dir data/reproject :results verbatim
  python ../../scripts/find-ratio.py \
         wr124-jwst-miri-2022-f1800w-radec.fits \
         wr124-jwst-miri-2022-f1280w-radec.fits \
         ratio-f1800w-f1280w-match-f1800w.fits \
         --bg-a 95.0 --bg-b 26.0 \
         --match-psf --debug --match-psf-to jwst-f1800w
#+end_src

#+RESULTS:
: Pixel scale: 0.0310 arcseconds
: Wavelengths: Filter A = 18.00 Filter B = 12.80
: PSF FWHM (pixels): Filter A = 19.2 Filter B = 13.6 Match to = 19.2

